// Long Island Coffee List — Shop Data
// No chains. Just real coffee.

const coffeeShops = [
  // ============================================================
  // WESTERN NASSAU / NYC-ADJACENT
  // ============================================================
  {
    id: "karak-house-great-neck",
    name: "Karak House Coffee Co",
    address: "12 Hicks Ln, Great Neck, NY",
    town: "Great Neck",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "646-570-2178",
    lat: 40.805903,
    lng: -73.734585,
    hours: {
      mon: "8:00 AM - 10:00 PM",
      tue: "8:00 AM - 10:00 PM",
      wed: "8:00 AM - 10:00 PM",
      thu: "8:00 AM - 10:00 PM",
      fri: "8:00 AM - 1:00 AM",
      sat: "10:00 AM - 1:00 AM",
      sun: "10:00 AM - 11:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "cakes", "cookies", "banana bread"],
    vibe: ["upscale", "open late", "chai-focused"],
    knownFor: "Spanish coffee latte, rose latte, Yemeni-style karak chai",
    description: "Elegant two-floor cafe, chai-focused, open late. Upstairs seating recommended.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/g7E2o0UmAcBBtTQumfj92A/o.jpg"
  },
  {
    id: "noir-bakery-great-neck",
    name: "NOIR Bakery & Cafe",
    address: "25 Cutter Mill Rd Unit 7, Great Neck, NY",
    town: "Great Neck",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-773-0973",
    lat: 40.781289,
    lng: -73.734026,
    hours: {
      mon: "7:00 AM - 3:00 PM",
      tue: "7:00 AM - 3:00 PM",
      wed: "7:00 AM - 3:00 PM",
      thu: "7:00 AM - 3:00 PM",
      fri: "7:00 AM - 3:00 PM",
      sat: "Closed",
      sun: "8:30 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["burekas", "shakshuka", "pastries", "breakfast"],
    vibe: ["small", "cozy"],
    knownFor: "Israeli street food + coffee",
    description: "Petite Israeli bakery/cafe with warm owners.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/as6EF8_6Qd7Km-ys9fviyw/o.jpg"
  },
  {
    id: "bean-and-bean-douglaston",
    name: "Bean & Bean Queens — Roastery & Cafe",
    address: "252-29 Northern Blvd, Douglaston, NY",
    town: "Douglaston",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "347-235-0129",
    lat: 40.7685,
    lng: -73.7430,
    hours: {
      mon: "7:30 AM - 8:00 PM",
      tue: "7:30 AM - 8:00 PM",
      wed: "7:30 AM - 8:00 PM",
      thu: "7:30 AM - 8:00 PM",
      fri: "7:30 AM - 8:00 PM",
      sat: "7:30 AM - 8:00 PM",
      sun: "7:30 AM - 8:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: true, seating: "indoor" },
    food: ["sandwiches", "pastries"],
    vibe: ["spacious", "laptop-friendly", "loft-like"],
    knownFor: "On-site roasting, great remote work spot",
    description: "Spacious loft-like space with in-house roasting, popular for laptop work.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ad2MkOQlKYQoxQvXTonbTQ/o.jpg"
  },
  {
    id: "for-five-manhasset",
    name: "For Five Coffee",
    address: "292 Plandome Rd, Manhasset, NY",
    town: "Manhasset",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-918-9488",
    lat: 40.796697,
    lng: -73.699176,
    hours: {
      mon: "7:00 AM - 7:00 PM",
      tue: "7:00 AM - 7:00 PM",
      wed: "7:00 AM - 7:00 PM",
      thu: "7:00 AM - 7:00 PM",
      fri: "7:00 AM - 7:00 PM",
      sat: "7:00 AM - 7:00 PM",
      sun: "7:00 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["eggs benedict", "grilled cheese", "breakfast & lunch"],
    vibe: ["modern", "spacious", "laptop-friendly"],
    knownFor: "Quality espresso, matcha lattes",
    description: "Modern, clean, spacious. Good for working or catching up with friends.",
    photo: "https://img.restaurantguru.com/c520-Cafe-For-Five-Coffee-food.jpg"
  },
  {
    id: "buttercooky-manhasset",
    name: "Buttercooky Bakery & Cafe",
    address: "140 Plandome Rd, Manhasset, NY",
    town: "Manhasset",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-627-1600",
    lat: 40.794681,
    lng: -73.698439,
    hours: {
      mon: "6:30 AM - 8:00 PM",
      tue: "6:30 AM - 8:00 PM",
      wed: "6:30 AM - 8:00 PM",
      thu: "6:30 AM - 8:00 PM",
      fri: "6:30 AM - 8:00 PM",
      sat: "6:30 AM - 8:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "breakfast", "smoothies"],
    vibe: ["country bakery", "community hub"],
    knownFor: "Custom cakes, old-school bakery charm",
    description: "Country bakery feel, long-standing local favorite.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/dV18va0emYOkaqwMKaFdpA/o.jpg"
  },
  {
    id: "taste-of-paris-floral-park",
    name: "Taste of Paris Coffeehouse",
    address: "83-52 Langdale St, Floral Park, NY",
    town: "Floral Park",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: null,
    lat: 40.72907,
    lng: -73.701108,
    hours: {
      mon: "7:00 AM - 8:00 PM",
      tue: "7:00 AM - 8:00 PM",
      wed: "7:00 AM - 8:00 PM",
      thu: "7:00 AM - 8:00 PM",
      fri: "7:00 AM - 10:00 PM",
      sat: "8:00 AM - 10:00 PM",
      sun: "8:00 AM - 8:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["quiet", "unique decor"],
    knownFor: "Coconut banana latte, salted caramel latte, fun oversized cups",
    description: "Quiet local cafe with unique lighting. No photos on walls (owner preference).",
    photo: "https://img.restaurantguru.com/w550/h367/r5aa-dessert-Taste-of-Paris-Coffeehouse.jpg"
  },
  {
    id: "vida-coffee-franklin-square",
    name: "Vida Coffee Shop",
    address: "882 Hempstead Tpke, Franklin Square, NY",
    town: "Franklin Square",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: null,
    lat: 40.707315,
    lng: -73.672633,
    hours: {
      mon: "9:00 AM - 5:00 PM",
      tue: "9:00 AM - 5:00 PM",
      wed: "9:00 AM - 5:00 PM",
      thu: "9:00 AM - 5:00 PM",
      fri: "9:00 AM - 5:00 PM",
      sat: "9:00 AM - 5:00 PM",
      sun: "10:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["waffles", "cakes", "empanadas", "sandwiches"],
    vibe: ["Latin family-owned", "quiet"],
    knownFor: "Colombian cold brew, dulce de leche frappuccino",
    description: "Latin family-owned, peaceful, with plants and books to browse.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/vwkyv1ag2xFxaZqD3XUBXA/o.jpg"
  },
  {
    id: "ny-caffeine-franklin-square",
    name: "NY Caffeine",
    address: "797 Hempstead Tpke, Franklin Square, NY",
    town: "Franklin Square",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-216-1683",
    lat: 40.706704,
    lng: -73.669536,
    hours: {
      mon: "7:00 AM - 10:00 PM",
      tue: "7:00 AM - 10:00 PM",
      wed: "7:00 AM - 10:00 PM",
      thu: "7:00 AM - 10:00 PM",
      fri: "7:00 AM - 12:00 AM",
      sat: "7:00 AM - 12:00 AM",
      sun: "7:00 AM - 10:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: null, seating: "indoor+outdoor" },
    food: ["croissants", "crepes", "pastries"],
    vibe: ["unique decor", "outdoor seating", "open late"],
    knownFor: "Canned latte presentation, late hours",
    description: "Great decor, heated outdoor tent, unique drink presentation (canned lattes).",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ETSc_mtoe1GHBP_OppeOmA/o.jpg"
  },

  // ============================================================
  // CENTRAL NASSAU
  // ============================================================
  {
    id: "cafe-blessing-mineola",
    name: "Cafe Blessing",
    address: "47 Mineola Blvd, Mineola, NY",
    town: "Mineola",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-248-2169",
    lat: 40.73953,
    lng: -73.639741,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "8:30 AM - 3:00 PM",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["Korean snacks", "scallion bread", "bulgogi", "banana bread", "juice"],
    vibe: ["small", "cozy", "Korean-owned"],
    knownFor: "Chagaccino, strawberry matcha with fresh fruit, in-house roasting",
    description: "Tiny, cozy Korean-owned cafe that roasts their own beans.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/Hny2t9a0jp0B728QA8Gadw/o.jpg"
  },
  {
    id: "east-rock-garden-city",
    name: "East Rock Coffee",
    address: "653 Franklin Ave, Garden City, NY",
    town: "Garden City",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-280-2429",
    lat: 40.724791,
    lng: -73.63354,
    hours: {
      mon: "8:30 AM - 6:00 PM",
      tue: "8:30 AM - 6:00 PM",
      wed: "8:30 AM - 6:00 PM",
      thu: "8:30 AM - 6:00 PM",
      fri: "8:30 AM - 6:00 PM",
      sat: "8:30 AM - 6:00 PM",
      sun: "8:30 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["quesadillas", "french toast", "omelets", "brunch"],
    vibe: ["cozy", "unique decor", "trendy"],
    knownFor: "Brunch destination, London fog, espresso drinks",
    description: "Warm, colorful, unique decor with a huge local following (viral on Instagram).",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/-LyQ0Tqhjdv9HWIlCJxIxw/o.jpg"
  },
  {
    id: "for-five-garden-city",
    name: "For Five Coffee",
    address: "147 7th St, Garden City, NY",
    town: "Garden City",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-271-9100",
    lat: 40.725195,
    lng: -73.635668,
    hours: {
      mon: "7:00 AM - 8:30 PM",
      tue: "7:00 AM - 8:30 PM",
      wed: "7:00 AM - 8:30 PM",
      thu: "7:00 AM - 8:30 PM",
      fri: "7:00 AM - 8:30 PM",
      sat: "7:00 AM - 8:30 PM",
      sun: "7:00 AM - 8:30 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: true, seating: "indoor" },
    food: ["breakfast & lunch", "pastries"],
    vibe: ["modern", "laptop-friendly"],
    knownFor: "Good workspace, house-roasted coffee",
    description: "Open concept, well-lit, popular laptop/work spot.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/3Lkq9Ik6tZh1bIQV85DxmA/o.jpg"
  },
  {
    id: "oak-and-orange-mineola",
    name: "Oak & Orange",
    address: "91 Mineola Blvd, Mineola, NY",
    town: "Mineola",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-746-3809",
    lat: 40.741227,
    lng: -73.64052,
    hours: {
      mon: "8:00 AM - 3:00 PM",
      tue: "8:00 AM - 3:00 PM",
      wed: "8:00 AM - 3:00 PM",
      thu: "8:00 AM - 3:00 PM",
      fri: "8:00 AM - 3:00 PM",
      sat: "Closed",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "grilled cheese", "sandwiches"],
    vibe: ["trendy", "cozy"],
    knownFor: "Unique menu, beautiful interior, great lunch spot",
    description: "Elevated, curated, relaxing. Near the train station.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/V6SK1LEgtv_YwUD_ielaQg/o.jpg"
  },
  {
    id: "qahwah-house-westbury",
    name: "Qahwah House",
    address: "541 Old Country Rd, Westbury, NY",
    town: "Westbury",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-214-6143",
    lat: 40.747335,
    lng: -73.593154,
    hours: {
      mon: "8:00 AM - 11:00 PM",
      tue: "8:00 AM - 11:00 PM",
      wed: "8:00 AM - 11:00 PM",
      thu: "8:00 AM - 11:00 PM",
      fri: "8:00 AM - 1:00 AM",
      sat: "8:00 AM - 1:00 AM",
      sun: "8:00 AM - 11:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: true, seating: "indoor" },
    food: ["pastries", "Khaliat Alnahi", "desserts"],
    vibe: ["lively", "community hub", "open late"],
    knownFor: "Yemeni coffee imported from Yemen, roasted in-house, late hours",
    description: "Large, lively Yemeni coffee house. Social/community hangout.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/H0fBuMEBn-IjWb5mFqPJxQ/o.jpg"
  },
  {
    id: "ny-caffeine-westbury",
    name: "NY Caffeine",
    address: "1540 Old Country Rd, Westbury, NY",
    town: "Westbury",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: null,
    lat: 40.74651,
    lng: -73.596158,
    hours: {
      mon: "7:00 AM - 10:00 PM",
      tue: "7:00 AM - 10:00 PM",
      wed: "7:00 AM - 10:00 PM",
      thu: "7:00 AM - 10:00 PM",
      fri: "7:00 AM - 12:00 AM",
      sat: "7:00 AM - 12:00 AM",
      sun: "7:00 AM - 10:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["pastries"],
    vibe: ["charming", "cozy", "outdoor seating"],
    knownFor: "Canned latte presentation, seasonal specials",
    description: "Beautiful, cozy, with outdoor seating area.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/NFDTrl3TuQtOvcmiO0Rcbg/o.jpg"
  },
  {
    id: "early-bird-east-meadow",
    name: "The Early Bird Cafe",
    address: "1934a Hempstead Tpke, East Meadow, NY",
    town: "East Meadow",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-916-3884",
    lat: 40.722673,
    lng: -73.565306,
    hours: {
      mon: "Closed",
      tue: "8:00 AM - 7:00 PM",
      wed: "8:00 AM - 7:00 PM",
      thu: "8:00 AM - 7:00 PM",
      fri: "8:00 AM - 7:00 PM",
      sat: "8:00 AM - 7:00 PM",
      sun: "8:00 AM - 7:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avocado toast", "egg sandwiches", "sandwiches"],
    vibe: ["cozy", "laptop-friendly"],
    knownFor: "Best mocha latte on LI (per regulars), great brunch",
    description: "Cozy, welcoming, great for working.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/nqVT2jBcUouK91Ah-eLhcQ/o.jpg"
  },
  {
    id: "grami-caffe-malverne",
    name: "GRAMI CAFFE",
    address: "22A Church St, Malverne, NY",
    town: "Malverne",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-788-0385",
    lat: 40.675974,
    lng: -73.667134,
    hours: {
      mon: "6:00 AM - 7:00 PM",
      tue: "6:00 AM - 7:00 PM",
      wed: "6:00 AM - 7:00 PM",
      thu: "6:00 AM - 7:00 PM",
      fri: "6:00 AM - 7:00 PM",
      sat: "7:00 AM - 7:00 PM",
      sun: "7:00 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["vegan options", "pastries"],
    vibe: ["Greek/Mediterranean", "family-owned", "cozy"],
    knownFor: "Freddo espresso (hard to find on LI), locally roasted beans",
    description: "Greek/Mediterranean family-owned, warm hospitality, real ceramic cups.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/aXwRFtMoHALg3QgPmlKjlw/o.jpg"
  },

  // ============================================================
  // NORTH SHORE NASSAU
  // ============================================================
  {
    id: "sweet-harbor-roslyn",
    name: "Sweet Harbor Coffee",
    address: "1353 Old Northern Blvd, Roslyn, NY",
    town: "Roslyn",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.800706,
    lng: -73.649293,
    hours: {
      mon: "Closed",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "croissants"],
    vibe: ["Brooklyn-inspired", "cozy"],
    knownFor: "Iced salted caramel latte, matcha vanilla rose latte",
    description: "Brooklyn-inspired, cozy, limited seating but popular.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/fR8_ONJPGT0yfMbVvrTP1Q/o.jpg"
  },
  {
    id: "dianes-bakery-roslyn",
    name: "Diane's Bakery/Cafe",
    address: "23 Bryant Ave, Roslyn, NY",
    town: "Roslyn",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-621-2522",
    lat: 40.804072,
    lng: -73.646846,
    hours: {
      mon: "Closed",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["quiche", "pies", "cakes", "salads", "pasta"],
    vibe: ["charming", "outdoor seating", "trendy"],
    knownFor: "Best quiche on LI, gorgeous patio",
    description: "Charming garden seating, bustling, elevated cafe.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/i9JOfy7fJTm0e13JzctMOg/o.jpg"
  },
  {
    id: "17a-cafe-roslyn-heights",
    name: "17A Cafe",
    address: "17A Lincoln Ave, Roslyn Heights, NY",
    town: "Roslyn Heights",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-626-0510",
    lat: 40.791491,
    lng: -73.642389,
    hours: {
      mon: "9:00 AM - 5:00 PM",
      tue: "Closed",
      wed: "Closed",
      thu: "Closed",
      fri: "Closed",
      sat: "Closed",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["bagels", "acai bowls", "vegan options", "juice"],
    vibe: ["hidden gem", "family-owned"],
    knownFor: "Off-menu items, incredible personal service, lobster salad",
    description: "Tiny hidden gem, owner-operated by 'Scotty Bagel'. Monday only — check ahead!",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/BAduo1CLbC5i3xnceN1Wtg/o.jpg"
  },
  {
    id: "southdown-glen-cove",
    name: "Southdown Coffee",
    address: "149 Glen St Suite 2, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.864564,
    lng: -73.63146,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avocado toast", "grilled cheese", "scones", "pastries"],
    vibe: ["bright", "cozy"],
    knownFor: "House-roasted beans, consistently excellent across all locations",
    description: "Bright, relaxing, warm staff. Local roaster with multiple LI locations.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/r7Z9uKcTHxVZvM7a_OaRDg/o.jpg"
  },
  {
    id: "southdown-oyster-bay",
    name: "Southdown Coffee",
    address: "49 Audrey Ave, Oyster Bay, NY",
    town: "Oyster Bay",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.777247,
    lng: -73.497157,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["grilled cheese", "banana bread", "cornbread"],
    vibe: ["charming", "beachy"],
    knownFor: "Lavender latte (house-made syrup), olive oil cake",
    description: "Cute, classic, cozy seaside town cafe. Limited seating (worth the wait).",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/Sr7wCYE7WDw9aWfMkje2wA/o.jpg"
  },
  {
    id: "cafe-nicos-glen-cove",
    name: "Cafe Nico's",
    address: "221 Glen St B, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-671-1444",
    lat: 40.861706,
    lng: -73.622391,
    hours: {
      mon: null,
      tue: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      sun: null
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["gelato", "pastries"],
    vibe: ["Italian cafe", "cash only"],
    knownFor: "Authentic Italian espresso, boxing glove decor, cash only",
    description: "Old-school Little Italy feel. Cash only!",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/Kkej33qavA25KFD7T44uHA/o.jpg"
  },
  {
    id: "ready-coffee-glen-cove",
    name: "Ready Coffee",
    address: "96 Forest Ave, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.872719,
    lng: -73.622203,
    hours: {
      mon: "5:00 AM - 9:00 PM",
      tue: "5:00 AM - 9:00 PM",
      wed: "5:00 AM - 9:00 PM",
      thu: "5:00 AM - 9:00 PM",
      fri: "5:00 AM - 9:00 PM",
      sat: "5:00 AM - 9:00 PM",
      sun: "5:00 AM - 9:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: [],
    vibe: ["drive-thru", "grab-and-go"],
    knownFor: "Sugar-free options (diabetic friendly), fast drive-thru service",
    description: "Drive-thru only, two lanes, fast and friendly.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/0cL6KVPdCry2dk5qef0PVQ/o.jpg"
  },
  {
    id: "sea-cliff-daily-grind",
    name: "Sea Cliff Daily Grind",
    address: "230 Sea Cliff Ave, Sea Cliff, NY",
    town: "Sea Cliff",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-675-1187",
    lat: 40.849287,
    lng: -73.645218,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["vegan options", "wraps", "biscuits"],
    vibe: ["cozy"],
    knownFor: "Daily vegan specials (ask the counter)",
    description: "Casual cafe with daily vegan specials.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ZEj5xR_AIEEAPhfnNTaQlA/o.jpg"
  },
  {
    id: "dessertino-sea-cliff",
    name: "Dessertino - The Crafty Spoon",
    address: "227 Glen Cove Ave, Sea Cliff, NY",
    town: "Sea Cliff",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-817-9421",
    lat: 40.847491,
    lng: -73.635954,
    hours: {
      mon: "10:00 AM - 9:30 PM",
      tue: "10:00 AM - 9:30 PM",
      wed: "10:00 AM - 9:30 PM",
      thu: "10:00 AM - 9:30 PM",
      fri: "10:00 AM - 10:30 PM",
      sat: "10:00 AM - 10:30 PM",
      sun: "10:00 AM - 9:30 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["desserts", "gelato", "kebabs"],
    vibe: ["cozy", "artsy", "laptop-friendly"],
    knownFor: "Pistachio tiramisu, multi-cultural dessert menu",
    description: "Warm, artsy, book-friendly. Great for reading.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/YDh3DCfuyHpbQcI1tLXgXA/o.jpg"
  },
  {
    id: "st-roccos-glen-cove",
    name: "St. Rocco's Bakery",
    address: "4 St Rocco Pl, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-427-5333",
    lat: 40.855741,
    lng: -73.618156,
    hours: {
      mon: "7:00 AM - 7:00 PM",
      tue: "7:00 AM - 7:00 PM",
      wed: "7:00 AM - 7:00 PM",
      thu: "7:00 AM - 7:00 PM",
      fri: "7:00 AM - 7:00 PM",
      sat: "7:00 AM - 7:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["croissants", "cakes", "eclairs", "semolina bread"],
    vibe: ["Italian cafe"],
    knownFor: "Best Italian bakery on Long Island (per many locals)",
    description: "Legendary Italian bakery, can have long holiday lines.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/qfzUUSQWXbpY5VP_I2gwRw/o.jpg"
  },

  // ============================================================
  // SOUTH SHORE NASSAU
  // ============================================================
  {
    id: "space-cowboy-long-beach",
    name: "Space Cowboy Coffee Co",
    address: "511 Long Beach Blvd, Long Beach, NY",
    town: "Long Beach",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-544-1665",
    lat: 40.590557,
    lng: -73.658355,
    hours: {
      mon: "6:00 AM - 4:00 PM",
      tue: "6:00 AM - 4:00 PM",
      wed: "6:00 AM - 4:00 PM",
      thu: "6:00 AM - 4:00 PM",
      fri: "6:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 1:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["light bites"],
    vibe: ["artsy", "beachy"],
    knownFor: "Cherry lemonade, salty sap iced latte, cool vibes",
    description: "Artsy, beachy, great artwork on walls.",
    photo: "https://spacecowboycoffee.com/cdn/shop/files/kenyatempbagimage.jpg?v=1700666440"
  },
  {
    id: "long-beach-coffee-tee",
    name: "Long Beach Coffee & Tee",
    address: "220 W Park Ave, Long Beach, NY",
    town: "Long Beach",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-608-9333",
    lat: 40.588086,
    lng: -73.670429,
    hours: {
      mon: "8:00 AM - 11:00 PM",
      tue: "8:00 AM - 11:00 PM",
      wed: "8:00 AM - 11:00 PM",
      thu: "8:00 AM - 11:00 PM",
      fri: "8:00 AM - 12:00 AM",
      sat: "8:00 AM - 12:00 AM",
      sun: "8:00 AM - 9:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "desserts"],
    vibe: ["unique decor", "golf simulator", "open late"],
    knownFor: "Golf simulators you can rent, good evening hangout",
    description: "Coffee shop + golf simulator combo!",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/_9bOUkL9PWPRG3iTmOV1fg/o.jpg"
  },
  {
    id: "no-rush-freeport",
    name: "No Rush Cafe",
    address: "399 S Main St, Freeport, NY",
    town: "Freeport",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-262-3289",
    lat: 40.646548,
    lng: -73.575227,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 6:30 PM",
      wed: "7:00 AM - 6:30 PM",
      thu: "7:00 AM - 6:30 PM",
      fri: "7:00 AM - 6:30 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: true, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "cinnamon rolls", "pastries"],
    vibe: ["cozy", "family-friendly"],
    knownFor: "Biscoff latte, sugar cookie latte, cozy 'no rush' atmosphere",
    description: "Cozy living-room feel, games for kids, books.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/3jYnNSxtjXeyzc5Khh1KJA/o.jpg"
  },
  {
    id: "ready-coffee-freeport",
    name: "Ready Coffee",
    address: "177 Atlantic Ave, Freeport, NY",
    town: "Freeport",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: null,
    lat: 40.645728,
    lng: -73.582415,
    hours: {
      mon: "5:00 AM - 6:00 PM",
      tue: "5:00 AM - 6:00 PM",
      wed: "5:00 AM - 6:00 PM",
      thu: "5:00 AM - 6:00 PM",
      fri: "5:00 AM - 6:00 PM",
      sat: "5:00 AM - 6:00 PM",
      sun: "5:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: [],
    vibe: ["drive-thru", "grab-and-go"],
    knownFor: "Shakes, customizable drinks, friendly staff",
    description: "Drive-thru, fast service.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/_f4-t-CnMSiu5Pw0dtCdyw/o.jpg"
  },
  {
    id: "rs-beanery-merrick",
    name: "RS Beanery",
    address: "153 Merrick Ave, Merrick, NY",
    town: "Merrick",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-208-7887",
    lat: 40.668333,
    lng: -73.554364,
    hours: {
      mon: "8:00 AM - 12:30 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: [],
    vibe: ["cozy"],
    knownFor: "Signature iced lattes, Friday evening hours",
    description: "Comfy, cozy, great atmosphere.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/2MEYvwuC-VbHw3jZD2fsBw/o.jpg"
  },
  {
    id: "hard-bean-merrick",
    name: "Hard Bean",
    address: "15 Merrick Ave, Merrick, NY",
    town: "Merrick",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "631-304-6647",
    lat: 40.691917,
    lng: -73.561894,
    hours: {
      mon: "6:00 AM - 6:00 PM",
      tue: "6:00 AM - 6:00 PM",
      wed: "6:00 AM - 6:00 PM",
      thu: "6:00 AM - 6:00 PM",
      fri: "6:00 AM - 6:00 PM",
      sat: "8:00 AM - 6:00 PM",
      sun: "8:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "sandwiches", "croissants"],
    vibe: ["modern", "unique decor"],
    knownFor: "Cookie butter shaken espresso, tiramisu latte, matcha",
    description: "Crisp, clean, intentional decor, coffee bean scent, gentle music.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/YudHrfS5OqkEMJnrymEzpA/o.jpg"
  },
  {
    id: "coffee-barn-merrick",
    name: "Coffee Barn",
    address: "2081 Merrick Rd, Merrick, NY",
    town: "Merrick",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-517-2154",
    lat: 40.65778,
    lng: -73.547361,
    hours: {
      mon: "6:00 AM - 9:00 PM",
      tue: "6:00 AM - 9:00 PM",
      wed: "6:00 AM - 9:00 PM",
      thu: "6:00 AM - 9:00 PM",
      fri: "6:00 AM - 9:00 PM",
      sat: "6:00 AM - 9:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: ["donuts"],
    vibe: ["drive-thru", "trendy"],
    knownFor: "Pumpkin lattes served in real pumpkins, Instagram/TikTok aesthetic",
    description: "Drive-thru barn, heavily seasonal/themed (TikTok famous).",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/pjooEMDJQAfWMGYqudnJ_w/o.jpg"
  },
  {
    id: "pink-cafe-rockville-centre",
    name: "The Pink Cafe & Bakery",
    address: "24 N Park Ave, Rockville Centre, NY",
    town: "Rockville Centre",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-344-5340",
    lat: 40.657088,
    lng: -73.645359,
    hours: {
      mon: "12:00 PM - 8:00 PM",
      tue: "10:00 AM - 8:00 PM",
      wed: "10:00 AM - 8:00 PM",
      thu: "10:00 AM - 8:00 PM",
      fri: "10:00 AM - 8:00 PM",
      sat: "10:00 AM - 8:00 PM",
      sun: "10:00 AM - 8:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "cookies"],
    vibe: ["unique decor", "charming", "party-friendly"],
    knownFor: "Oatmilk vanilla matcha latte, tea parties, Bridgerton vibes",
    description: "Pink-themed, cute, great for girls' events/parties.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/RnOThUhY00kE3spUsMT0MA/o.jpg"
  },
  {
    id: "flour-shoppe-rockville-centre",
    name: "The Flour Shoppe Cafe",
    address: "41 S Park Ave, Rockville Centre, NY",
    town: "Rockville Centre",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-442-1299",
    lat: 40.654763,
    lng: -73.645909,
    hours: {
      mon: "8:00 AM - 2:00 PM",
      tue: "8:00 AM - 2:00 PM",
      wed: "8:00 AM - 2:00 PM",
      thu: "8:00 AM - 2:00 PM",
      fri: "8:00 AM - 2:00 PM",
      sat: "8:00 AM - 2:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["brunch", "chips", "cookies"],
    vibe: ["brunch spot", "outdoor seating"],
    knownFor: "Honey lavender latte, brunch spot",
    description: "Elevated brunch cafe with a nice outdoor area.",
    photo: "https://images.squarespace-cdn.com/content/v1/5dca4ac513b480335fc9ec2c/1576009616262-5WSBSSWXC3Z6QLBGDAC3/RVC+Store+2.jpeg"
  },

  // ============================================================
  // WESTERN SUFFOLK
  // ============================================================
  {
    id: "beehive-huntington",
    name: "Beehive Espresso Bar",
    address: "176 New York Ave, Huntington, NY",
    town: "Huntington",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-546-8070",
    lat: 40.876319,
    lng: -73.423304,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "8:00 AM - 7:00 PM",
      sun: "8:00 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["baklava", "croissants", "pastries", "gelato"],
    vibe: ["cozy", "unique decor"],
    knownFor: "Intentional specialty coffee, latte art, Turkish baklava",
    description: "Warm yellow honeycomb decor, sofas + easy chairs, real dishes (not disposable), next to Heckscher Park.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/_2TSulQ7Zg-W9pbIOh61Hg/o.jpg"
  },
  {
    id: "special-cup-huntington",
    name: "The Special Cup",
    address: "387 New York Ave, Huntington, NY",
    town: "Huntington",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-470-4697",
    lat: 40.869432,
    lng: -73.426131,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["breakfast & lunch", "avocado toast", "pastries"],
    vibe: ["artsy", "cozy", "trendy"],
    knownFor: "Exhaustive flavored latte list, great brunch, formerly 'Soul Brew'",
    description: "Artsy, homey, vibey music. Good for working or socializing.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/7ARHxMKoKAze0CsaXCBDxg/o.jpg"
  },
  {
    id: "southdown-huntington",
    name: "Southdown Coffee",
    address: "210 Wall St Unit B, Huntington, NY",
    town: "Huntington",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.872697,
    lng: -73.427549,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "pastries", "scones"],
    vibe: ["bright", "modern"],
    knownFor: "House-roasted coffee, the egg sandwich",
    description: "Bright, clean, narrow but inviting. House-made syrups.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/IRuEpY5JAz_W5b8RgfQj2w/o.jpg"
  },
  {
    id: "nautilus-huntington-station",
    name: "Nautilus Roasting Co",
    address: "1000 New York Ave Unit A, Huntington Station, NY",
    town: "Huntington Station",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.845743,
    lng: -73.411752,
    hours: {
      mon: "6:30 AM - 4:00 PM",
      tue: "6:30 AM - 4:00 PM",
      wed: "6:30 AM - 4:00 PM",
      thu: "6:30 AM - 4:00 PM",
      fri: "6:30 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: "plenty", seating: "indoor" },
    food: ["breakfast burritos", "pies", "macarons"],
    vibe: ["artsy", "vegan", "community hub"],
    knownFor: "Vegan coffee house, community events (open mic, run club, markets), in-house roasting",
    description: "Victorian living room meets eclectic art — weird and awesome. Vegan cafe. Lots of outlets.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/mqzBeZhIWzoLlRw2CXaomg/o.jpg"
  },
  {
    id: "brewology-huntington-station",
    name: "Brewology Coffee",
    address: "556 E Jericho Tpke, Huntington Station, NY",
    town: "Huntington Station",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-470-3960",
    lat: 40.832663,
    lng: -73.390466,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: "some", seating: "indoor" },
    food: ["cookies", "pastries"],
    vibe: ["charming", "lively", "grab-and-go"],
    knownFor: "Chagaccino, strawberry matcha, seasonal specials",
    description: "Cute, fun, music a bit loud. More grab-and-go than sit-and-work.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/UKKA_J5o9yxVkFaDKIO26Q/o.jpg"
  },
  {
    id: "cold-spring-harbor-cafe",
    name: "Cold Spring Harbor Cafe",
    address: "85 Main St, Cold Spring Harbor, NY",
    town: "Cold Spring Harbor",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.870782,
    lng: -73.458576,
    hours: {
      mon: "7:15 AM - 5:00 PM",
      tue: "7:15 AM - 5:00 PM",
      wed: "7:15 AM - 5:00 PM",
      thu: "7:15 AM - 5:00 PM",
      fri: "7:15 AM - 5:00 PM",
      sat: "7:15 AM - 5:00 PM",
      sun: "7:15 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["small", "local", "family-friendly"],
    knownFor: "Cinnamon toast crunch latte, seasonal pumpkin/snowman cups",
    description: "Small, locally owned, kid-friendly, fresh-paint-new feel.",
    photo: "https://img.marinas.com/v2/d1b10a89de0da68ae38c2135a7fc988398d1e84a6ccd5d6317369b1b82f4642e.jpg"
  },
  {
    id: "sweetie-pies-cold-spring-harbor",
    name: "Sweetie Pies on Main",
    address: "181 Main St, Cold Spring Harbor, NY",
    town: "Cold Spring Harbor",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-367-9500",
    lat: 40.871404,
    lng: -73.456856,
    hours: {
      mon: "7:30 AM - 4:00 PM",
      tue: "7:30 AM - 4:00 PM",
      wed: "7:30 AM - 4:00 PM",
      thu: "7:30 AM - 4:00 PM",
      fri: "7:30 AM - 4:00 PM",
      sat: "7:30 AM - 5:00 PM",
      sun: "7:30 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["pastries", "cookies", "chocolate danish"],
    vibe: ["charming", "dog-friendly"],
    knownFor: "Adorable aesthetic, great post-hike stop",
    description: "Quaint, New England charm, dog-friendly garden, indoor + outdoor seating.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/JsR1rEbXv9TlrsEbZx3aFQ/o.jpg"
  },
  {
    id: "gourmet-whaler-cold-spring-harbor",
    name: "The Gourmet Whaler",
    address: "111 Main St, Cold Spring Harbor, NY",
    town: "Cold Spring Harbor",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-659-2977",
    lat: 40.870927,
    lng: -73.458202,
    hours: {
      mon: "8:00 AM - 4:00 PM",
      tue: "8:00 AM - 4:00 PM",
      wed: "Closed",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["shrimp tacos", "quinoa bowls", "wraps", "gelato", "pastries"],
    vibe: [],
    knownFor: "Multi-concept (bakery + ice cream + cafe + lunch), Nutella latte",
    description: "Multi-concept: bakery + ice cream + cafe + lunch.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/PFTHfN_ik10FyfSilAQeXA/o.jpg"
  },
  {
    id: "southdown-northport",
    name: "Southdown Coffee",
    address: "72 Main St, Northport, NY",
    town: "Northport",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.900053,
    lng: -73.350724,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "scones", "zucchini bread"],
    vibe: ["charming", "local"],
    knownFor: "Consistent Southdown quality, apple crumb",
    description: "Cute, local, Main Street charm.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/IdAaW6DDuYtyAl4yeH3w3g/o.jpg"
  },
  {
    id: "the-barn-east-northport",
    name: "The Barn",
    address: "430 Larkfield Rd, East Northport, NY",
    town: "East Northport",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.865342,
    lng: -73.321619,
    hours: {
      mon: "8:00 AM - 6:00 PM",
      tue: "8:00 AM - 6:00 PM",
      wed: "8:00 AM - 6:00 PM",
      thu: "8:00 AM - 6:00 PM",
      fri: "8:00 AM - 6:00 PM",
      sat: "8:00 AM - 6:00 PM",
      sun: "8:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: [],
    vibe: ["trendy", "drive-thru"],
    knownFor: "Pumpkin spice latte in a real pumpkin, holiday themed drinks",
    description: "Instagram-famous seasonal drinks, drive-thru concept.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/7n802-j9GCkM_SXZuMXYyA/o.jpg"
  },
  {
    id: "babylon-bean-babylon",
    name: "Babylon Bean Coffee House",
    address: "17 Fire Island Ave, Babylon, NY",
    town: "Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-587-7729",
    lat: 40.696142,
    lng: -73.323161,
    hours: {
      mon: "4:45 AM - 7:00 PM",
      tue: "4:45 AM - 7:00 PM",
      wed: "4:45 AM - 7:00 PM",
      thu: "4:45 AM - 7:00 PM",
      fri: "4:45 AM - 9:00 PM",
      sat: "4:45 AM - 9:00 PM",
      sun: "5:45 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["bagels", "pastries"],
    vibe: ["artsy", "historic", "cozy"],
    knownFor: "Cold brew display, opens insanely early (4:45am!), art gallery space",
    description: "Art gallery + coffee house, old school architecture, cozy but can feel cramped.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/KW9lA9HWkDMMHjagRELdmA/o.jpg"
  },
  {
    id: "jack-jacks-babylon",
    name: "Jack Jack's Coffee House",
    address: "223 Deer Park Ave, Babylon, NY",
    town: "Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-885-3722",
    lat: 40.699812,
    lng: -73.322271,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 12:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "salads", "sandwiches", "cookies"],
    vibe: ["artsy", "dog-friendly"],
    knownFor: "Homemade mocha/caramel sauces, local art, all-day egg sandwich",
    description: "Art gallery meets coffee shop, dog-friendly.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ZDkoVJpjMbWq-YiBYv01Ng/o.jpg"
  },
  {
    id: "sergi-west-babylon",
    name: "Sergi Coffee Roaster",
    address: "780 Sunrise Hwy, West Babylon, NY",
    town: "West Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-539-8006",
    lat: 40.71349,
    lng: -73.337973,
    hours: {
      mon: "Closed",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "9:00 AM - 2:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "sandwiches"],
    vibe: ["roastery"],
    knownFor: "In-house roasting, great value espresso ($3.35 double espresso!)",
    description: "In-house roasting with great value espresso.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/7Yz0XgwB6Iliy2bW0VKW3A/o.jpg"
  },
  {
    id: "north-babylon-bean",
    name: "North Babylon Bean Coffee House",
    address: "775 Deer Pk Rd, North Babylon, NY",
    town: "North Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-314-4073",
    lat: 40.712752,
    lng: -73.321406,
    hours: {
      mon: "5:00 AM - 4:00 PM",
      tue: "5:00 AM - 4:00 PM",
      wed: "5:00 AM - 4:00 PM",
      thu: "5:00 AM - 4:00 PM",
      fri: "5:00 AM - 4:00 PM",
      sat: "5:00 AM - 4:00 PM",
      sun: "6:00 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avocado toast", "pastries", "breakfast"],
    vibe: ["family-owned", "community hub"],
    knownFor: "Vietnamese iced coffee, hazelnut brewed from bean, roasts on-site",
    description: "Friendly owner (Ryan) who knows everyone by name. Brewing visible in back.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/SyqjofeqIOoU4QMd9IR6PA/o.jpg"
  },
  {
    id: "east-end-roasters-north-babylon",
    name: "East End Coffee Roasters",
    address: "775 Deer Park Ave, North Babylon, NY",
    town: "North Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-400-6699",
    lat: 40.723353,
    lng: -73.322708,
    hours: {
      mon: "6:30 AM - 3:30 PM",
      tue: "6:30 AM - 3:30 PM",
      wed: "6:30 AM - 3:30 PM",
      thu: "6:30 AM - 3:30 PM",
      fri: "6:30 AM - 3:30 PM",
      sat: "7:00 AM - 2:00 PM",
      sun: "7:00 AM - 1:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: [],
    vibe: ["roastery"],
    knownFor: "Whole bean roaster, ships nationwide, house blends",
    description: "Whole bean roaster that ships nationwide.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ij8HrNq09AYxNS0T0ZuOwg/o.jpg"
  },
  {
    id: "so-sveglio-lindenhurst",
    name: "So Sveglio Espresso Bar",
    address: "124 S Wellwood Ave, Lindenhurst, NY",
    town: "Lindenhurst",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-412-3750",
    lat: 40.686641,
    lng: -73.372979,
    hours: {
      mon: "9:00 AM - 6:00 PM",
      tue: "8:00 AM - 6:00 PM",
      wed: "8:00 AM - 6:00 PM",
      thu: "8:00 AM - 6:00 PM",
      fri: "8:00 AM - 6:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "10:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["gelato", "cannolis", "pastries"],
    vibe: ["Italian cafe"],
    knownFor: "Italian espresso bar, gelato catering for events",
    description: "Italian espresso bar with gelato catering for events.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/CbLscThdumRjIGfsexDT1w/o.jpg"
  },
  {
    id: "munis-lindenhurst",
    name: "Muni's Coffee Joint",
    address: "222 N Wellwood Ave, Lindenhurst, NY",
    town: "Lindenhurst",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-412-5085",
    lat: 40.689247,
    lng: -73.375726,
    hours: {
      mon: "6:00 AM - 4:00 PM",
      tue: "6:00 AM - 4:00 PM",
      wed: "6:00 AM - 4:00 PM",
      thu: "6:00 AM - 4:00 PM",
      fri: "6:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "muffins", "vegan options"],
    vibe: ["Brazilian vibes", "cozy", "trendy", "family-friendly"],
    knownFor: "Great iced coffee, chill atmosphere, live music vibes",
    description: "Brazilian vibes, cozy, trendy, books + toys for kids.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/j2Do6tQkLm07bpOZvUCnVw/o.jpg"
  },
  {
    id: "milano-bean-bay-shore",
    name: "Milano Bean Cafe",
    address: "6 E Main St, Bay Shore, NY",
    town: "Bay Shore",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-328-1529",
    lat: 40.721454,
    lng: -73.24743,
    hours: {
      mon: "7:00 AM - 10:00 PM",
      tue: "7:00 AM - 10:00 PM",
      wed: "7:00 AM - 10:00 PM",
      thu: "7:00 AM - 10:00 PM",
      fri: "7:00 AM - 11:00 PM",
      sat: "7:00 AM - 11:00 PM",
      sun: "7:00 AM - 10:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["community hub", "cozy", "open late"],
    knownFor: "Fruity pebble matcha, strawberry cheesecake latte, late hours",
    description: "Community hangout — people off phones, studying or socializing. Comfy sofas.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/2jOG1thf6HI359HNz5KgGA/o.jpg"
  },

  // ============================================================
  // CENTRAL/EASTERN SUFFOLK
  // ============================================================
  {
    id: "my-towns-cafe-east-islip",
    name: "My Town's Cafe",
    address: "51 W Main St, East Islip, NY",
    town: "East Islip",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-446-4089",
    lat: 40.730755,
    lng: -73.193354,
    hours: {
      mon: "9:00 AM - 9:00 PM",
      tue: "6:00 AM - 9:00 PM",
      wed: "6:00 AM - 9:00 PM",
      thu: "6:00 AM - 9:00 PM",
      fri: "6:00 AM - 9:00 PM",
      sat: "7:00 AM - 9:00 PM",
      sun: "7:00 AM - 8:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: null, seating: "indoor" },
    food: ["quiche", "croissants", "tiramisu", "sandwiches"],
    vibe: ["rustic", "unique decor", "trendy"],
    knownFor: "Cinnamon bun foam lattes, Irish cream cold brew, Instagram-worthy decor",
    description: "Rustic dark wood, string lights, husband-and-wife owned.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/rPVhwzpI-CeHuxFIQM1m0g/o.jpg"
  },
  {
    id: "dark-horse-sayville",
    name: "Dark Horse Coffee & Kitchen",
    address: "4836 Sunrise Hwy, Sayville, NY",
    town: "Sayville",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-256-6988",
    lat: 40.756263,
    lng: -73.108608,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "8:00 AM - 2:00 PM",
      sun: "8:00 AM - 2:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["breakfast burritos", "avocado toast", "breakfast"],
    vibe: ["cozy", "wellness"],
    knownFor: "Shaken honey espresso, shroom latte, German tourists rave about it",
    description: "Warm, music + books in background, 7 tables, no rush.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/n1keLK2l_vKmf69G-QyT6w/o.jpg"
  },
  {
    id: "sayville-bean",
    name: "Sayville Bean Coffee House",
    address: "59 W Main St, Sayville, NY",
    town: "Sayville",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-319-5637",
    lat: 40.729817,
    lng: -73.093749,
    hours: {
      mon: "5:00 AM - 7:30 PM",
      tue: "5:00 AM - 7:30 PM",
      wed: "5:00 AM - 7:30 PM",
      thu: "5:00 AM - 7:30 PM",
      fri: "5:00 AM - 7:30 PM",
      sat: "5:00 AM - 7:30 PM",
      sun: "5:30 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: true, outlets: null, seating: "indoor" },
    food: ["wraps", "smoothies", "egg sandwiches"],
    vibe: ["community hub", "live music"],
    knownFor: "Live music, cold brew production visible on-site, early hours",
    description: "Classic community coffee house.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/jT4zuFpd9uwOLqGmElat7A/o.jpg"
  },
  {
    id: "brownstones-sayville",
    name: "Brownstones Coffee Sayville",
    address: "229 W Main St, Sayville, NY",
    town: "Sayville",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-567-5376",
    lat: 40.733613,
    lng: -73.087553,
    hours: {
      mon: "7:30 AM - 3:00 PM",
      tue: "7:30 AM - 3:00 PM",
      wed: "7:30 AM - 3:00 PM",
      thu: "7:30 AM - 3:00 PM",
      fri: "7:30 AM - 3:30 PM",
      sat: "7:30 AM - 3:30 PM",
      sun: "7:30 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["frittata", "pancakes", "salads", "cocktails"],
    vibe: ["charming", "brunch spot"],
    knownFor: "Gourmet brunch, themed drinks, mimosas",
    description: "Cute, quaint brunch spot.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/-Nvc150Ik5IuTlapQ55pLw/o.jpg"
  },
  {
    id: "kings-coast-bohemia",
    name: "Kings Coast Coffee Company",
    address: "55 Carlough Rd, Bohemia, NY",
    town: "Bohemia",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-238-1666",
    lat: 40.757218,
    lng: -73.1085,
    hours: {
      mon: "8:00 AM - 5:00 PM",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "9:00 AM - 4:00 PM",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: [],
    vibe: ["roastery"],
    knownFor: "In-house roasting, 4-shot large lattes, Bowbreaker roast, Lifeline espresso",
    description: "Hidden in an industrial park, roastery visible through glass. Serious coffee.",
    photo: "https://cdn.shopify.com/s/files/1/2332/1547/files/2E8A1213_1400x.jpg?v=1643574132"
  },
  {
    id: "coho-patchogue",
    name: "CoHo Coffee House",
    address: "62 W Main St, Patchogue, NY",
    town: "Patchogue",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-569-4900",
    lat: 40.765682,
    lng: -73.016369,
    hours: {
      mon: "6:00 AM - 6:00 PM",
      tue: "6:00 AM - 6:00 PM",
      wed: "6:00 AM - 6:00 PM",
      thu: "6:00 AM - 8:00 PM",
      fri: "6:00 AM - 9:00 PM",
      sat: "6:00 AM - 9:00 PM",
      sun: "6:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["juice", "banana bread", "cookies"],
    vibe: ["cozy", "laptop-friendly"],
    knownFor: "Creme brulee iced latte, cottage core chai, expanding to new locations",
    description: "Warm, welcoming, good for remote work or reading.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/TCT-bdYrEpv378tOZgHF3w/o.jpg"
  },
  {
    id: "southdown-patchogue",
    name: "Southdown Coffee",
    address: "16 Havens Ave, Patchogue, NY",
    town: "Patchogue",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: null,
    lat: 40.766034,
    lng: -73.016873,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["sandwiches", "cookies"],
    vibe: ["bright", "spacious", "unique decor"],
    knownFor: "Great drip coffee, peaceful afternoon escape",
    description: "Big windows, plants, bright/spacious. Leather sofa + plant vibes.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/eJtHut7Hlg6wXrKGjot50Q/o.jpg"
  },
  {
    id: "toast-patchogue",
    name: "Toast Coffee + Kitchen",
    address: "46 E Main St, Patchogue, NY",
    town: "Patchogue",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-654-7091",
    lat: 40.765318,
    lng: -73.013836,
    hours: {
      mon: "8:00 AM - 3:00 PM",
      tue: "8:00 AM - 3:00 PM",
      wed: "8:00 AM - 3:00 PM",
      thu: "8:00 AM - 3:00 PM",
      fri: "8:00 AM - 3:00 PM",
      sat: "7:30 AM - 3:30 PM",
      sun: "7:30 AM - 3:30 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["eggs benedict", "french toast", "scrambled eggs", "brunch"],
    vibe: ["lively", "brunch spot"],
    knownFor: "Massive brunch menu, pink mimosas, always packed",
    description: "Popular brunch spot, bustling, counter + table seating.",
    photo: "https://patch.com/img/cdn20/users/24390794/20220413/040753/styles/patch_image/public/roast-coffee___13160740352.png"
  },
  {
    id: "brewport-bellport",
    name: "Brewport Coffee House",
    address: "129 S Country Rd, Bellport, NY",
    town: "Bellport",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-803-0809",
    lat: 40.757549,
    lng: -72.939315,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: "plenty", seating: "indoor" },
    food: ["pastries"],
    vibe: ["cozy", "laptop-friendly", "quiet"],
    knownFor: "Best remote work spot in Suffolk (fast WiFi, outlets, quiet), sweater weather chai",
    description: "Cozy, great for remote work. Background music at perfect volume. Window nook + couch.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/hbMnUvMpFaZVBiBpCY7xXw/o.jpg"
  },
  {
    id: "bellport-apothecary",
    name: "Bellport Apothecary",
    address: "151 S Country Rd, Bellport, NY",
    town: "Bellport",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-431-6825",
    lat: 40.757992,
    lng: -72.938732,
    hours: {
      mon: "8:00 AM - 5:00 PM",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["scones", "smoothies", "light bites"],
    vibe: ["upscale", "wellness", "charming"],
    knownFor: "Lavender lemonade tea, organic skincare products + coffee",
    description: "Coffee + boutique + wellness shop, outdoor seating, Bellport Village charm.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/HJiKqRhe2F7Sq96Ztx2UWw/o.jpg"
  },

  // ============================================================
  // NORTH FORK
  // ============================================================
  {
    id: "pips-greenport",
    name: "Pip's Cafe & Provisions",
    address: "218 Main St, Greenport, NY",
    town: "Greenport",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-318-0363",
    lat: 41.102922,
    lng: -72.358913,
    hours: {
      mon: "7:30 AM - 3:00 PM",
      tue: "Closed",
      wed: "7:30 AM - 3:00 PM",
      thu: "7:30 AM - 3:00 PM",
      fri: "7:30 AM - 4:00 PM",
      sat: "7:30 AM - 4:00 PM",
      sun: "7:30 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["sandwiches", "avocado toast", "croissants", "egg sandwiches"],
    vibe: ["artsy"],
    knownFor: "Counter Culture coffee, La Marzocco espresso, vintage records",
    description: "Counter Culture coffee with vintage records.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/fkoO29J2381y3Lns1hvcLQ/o.jpg"
  },
  {
    id: "aldos-greenport",
    name: "Aldo's Coffee Company",
    address: "103-105 Front St, Greenport, NY",
    town: "Greenport",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-213-9353",
    lat: 41.102362,
    lng: -72.359831,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 7:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "8:30 AM - 10:30 AM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["gelato", "biscotti", "croissants", "pastries"],
    vibe: ["waterfront views", "outdoor seating"],
    knownFor: "In-house roasted coffee, biscotti gifts, hot chocolate, 10+ years running",
    description: "Waterfront views, patio overlooking harbor/carousel, ice cream + coffee.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/6YmgeLfGDnNxAKMG7aMdTQ/o.jpg"
  },
  {
    id: "blue-duck-greenport",
    name: "The Blue Duck Bakery Cafe",
    address: "130 Front St, Greenport, NY",
    town: "Greenport",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-333-2060",
    lat: 41.102155,
    lng: -72.361516,
    hours: {
      mon: "8:00 AM - 4:00 PM",
      tue: "8:00 AM - 4:00 PM",
      wed: "8:00 AM - 4:00 PM",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["cookies", "pastries", "pies"],
    vibe: ["charming"],
    knownFor: "European-style baking (originally from Southampton since 1999)",
    description: "Cute refurbished house, smells like butter, tables inside + alley seating.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/LGP3Zo36ccFyYGW2pA47WA/o.jpg"
  },
  {
    id: "north-fork-roasting-southold",
    name: "North Fork Roasting Co.",
    address: "55795 Main Rd, Southold, NY",
    town: "Southold",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-876-5450",
    lat: 40.966096,
    lng: -72.564002,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["muffins", "egg sandwiches", "pastries"],
    vibe: ["family-friendly", "event space"],
    knownFor: "In-house roasting, strawberry matcha, best third-wave coffee on North Fork",
    description: "Upstairs rooms including kids' playroom, outdoor space for bands/events.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/PELNeKeXFxQLcJOoQ2jpRw/o.jpg"
  },
  {
    id: "panoramica-peconic",
    name: "Panoramica",
    address: "2745 Peconic Ln, Peconic, NY",
    town: "Peconic",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-765-8354",
    lat: 41.046518,
    lng: -72.461432,
    hours: {
      mon: "Closed",
      tue: "Closed",
      wed: "8:00 AM - 3:00 PM",
      thu: "8:00 AM - 3:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["unique decor", "family-owned"],
    knownFor: "Unique design, amazing branding, creative energy",
    description: "Futuristic/retro ('The Jetsons'), fun sound effects in bathroom, owner-operated.",
    photo: "https://images.happycow.net/venues/1024/15/23/hcmp152310_1383911.jpeg"
  },
  {
    id: "love-lane-kitchen-mattituck",
    name: "Love Lane Kitchen",
    address: "240 Love Ln, Mattituck, NY",
    town: "Mattituck",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-298-8989",
    lat: 40.992056,
    lng: -72.534714,
    hours: {
      mon: "8:00 AM - 9:00 PM",
      tue: "8:00 AM - 4:00 PM",
      wed: "8:00 AM - 4:00 PM",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 9:00 PM",
      sat: "8:00 AM - 9:00 PM",
      sun: "8:00 AM - 9:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["lobster roll", "salads", "brunch", "cocktails"],
    vibe: ["dog-friendly", "farm-to-table"],
    knownFor: "Homemade chai latte, self-serve coffee refills, farm-to-table vibe",
    description: "Dog-friendly patio, self-serve coffee bar, cozy indoor/outdoor.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/a3n7n1HJ8YLrLv5j9H8cWg/o.jpg"
  },

  // ============================================================
  // SOUTH FORK / HAMPTONS
  // ============================================================
  {
    id: "hampton-coffee-water-mill",
    name: "Hampton Coffee Company",
    address: "869 Montauk Hwy, Water Mill, NY",
    town: "Water Mill",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-726-2633",
    lat: 40.912779,
    lng: -72.348484,
    hours: {
      mon: "5:15 AM - 5:00 PM",
      tue: "5:15 AM - 5:00 PM",
      wed: "5:15 AM - 5:00 PM",
      thu: "5:15 AM - 5:00 PM",
      fri: "5:15 AM - 5:00 PM",
      sat: "5:15 AM - 5:00 PM",
      sun: "5:15 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["breakfast & lunch", "Mexican food", "sandwiches", "pastries"],
    vibe: ["early bird"],
    knownFor: "Multiple Hamptons locations, opens at 5:15am, strong local loyalty",
    description: "Opens at 5:15am with full breakfast/lunch and strong local loyalty.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ExK6XYqjvlUVbBvCyc1eOw/o.jpg"
  },
  {
    id: "hampton-coffee-southampton",
    name: "Hampton Coffee Company",
    address: "749 County Rd 39A, Southampton, NY",
    town: "Southampton",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-353-3088",
    lat: 40.898958,
    lng: -72.373446,
    hours: {
      mon: "6:00 AM - 5:00 PM",
      tue: "6:00 AM - 5:00 PM",
      wed: "6:00 AM - 5:00 PM",
      thu: "6:00 AM - 5:00 PM",
      fri: "6:00 AM - 5:00 PM",
      sat: "6:00 AM - 5:00 PM",
      sun: "6:00 AM - 5:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: null, seating: "indoor" },
    food: ["sandwiches", "muffins"],
    vibe: ["cozy"],
    knownFor: "Friendly baristas, WiFi, good grab-and-go",
    description: "Friendly baristas, WiFi, good grab-and-go.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/TCB86JFL-4BpvwuxbGNk_g/o.jpg"
  },
  {
    id: "hampton-coffee-montauk",
    name: "Hampton Coffee Company",
    address: "732 Montauk Hwy, Montauk, NY",
    town: "Montauk",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-668-8206",
    lat: 41.033991,
    lng: -71.944957,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["bagels", "egg sandwiches", "pastries"],
    vibe: ["grab-and-go"],
    knownFor: "Cinnamon roll latte",
    description: "Solid grab-and-go in Montauk.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/7XlHVfnGzZQUAHwVFdU-JA/o.jpg"
  },
  {
    id: "golden-pear-southampton",
    name: "Golden Pear Cafe",
    address: "99 Main St, Southampton, NY",
    town: "Southampton",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-283-8900",
    lat: 40.809453,
    lng: -72.643482,
    hours: {
      mon: "6:30 AM - 5:30 PM",
      tue: "6:30 AM - 5:30 PM",
      wed: "6:30 AM - 5:30 PM",
      thu: "6:30 AM - 5:30 PM",
      fri: "6:30 AM - 5:30 PM",
      sat: "6:30 AM - 5:30 PM",
      sun: "6:30 AM - 4:30 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["scones", "breakfast burritos", "salads"],
    vibe: ["community hub"],
    knownFor: "Decades-old Hamptons staple, pricey but beloved by some",
    description: "Longtime neighborhood institution, community hub.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/0abosS4ZQ3Azyi5uvmC-HQ/o.jpg"
  },
  {
    id: "tutto-caffe-east-hampton",
    name: "Tutto Caffe",
    address: "55 Main St, East Hampton, NY",
    town: "East Hampton",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-771-9030",
    lat: 40.962902,
    lng: -72.186514,
    hours: {
      mon: "8:00 AM - 5:00 PM",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["pizza", "cookies", "cakes"],
    vibe: ["Italian cafe", "outdoor seating", "cocktails"],
    knownFor: "Paloma cocktails, Italian pastries, great patio",
    description: "Italian cafe with beautiful patio, cocktails available.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/klHbhOyHOthrIkArsLtwjw/o.jpg"
  },
  {
    id: "jacks-stir-brew-amagansett",
    name: "Jack's Stir Brew Coffee",
    address: "146 Montauk Hwy, Amagansett, NY",
    town: "Amagansett",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-267-5555",
    lat: 40.983294,
    lng: -72.142146,
    hours: {
      mon: "6:00 AM - 4:00 PM",
      tue: "6:00 AM - 4:00 PM",
      wed: "6:00 AM - 4:00 PM",
      thu: "6:00 AM - 4:00 PM",
      fri: "6:00 AM - 4:00 PM",
      sat: "6:00 AM - 4:00 PM",
      sun: "6:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "outdoor" },
    food: ["biscuits", "donuts", "vegan options"],
    vibe: ["wellness", "grab-and-go"],
    knownFor: "100% organic, triple ristretto shots only, Stella iced drink",
    description: "Grab-and-go focused, minimal seating, organic coffee, picnic tables outside.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/BnMaekHUPxM7Xtv_Puf5VQ/o.jpg"
  },
  {
    id: "sett-coffee-amagansett",
    name: "Sett Coffee",
    address: "136 Main St, Amagansett, NY",
    town: "Amagansett",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-256-7831",
    lat: 40.97572,
    lng: -72.140378,
    hours: {
      mon: "Closed",
      tue: "Closed",
      wed: "7:00 AM - 1:00 PM",
      thu: "7:00 AM - 1:00 PM",
      fri: "7:00 AM - 1:00 PM",
      sat: "7:00 AM - 1:00 PM",
      sun: "7:00 AM - 1:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["donuts", "breakfast"],
    vibe: ["small", "community hub"],
    knownFor: "Excellent beans, becoming a daily ritual for locals",
    description: "New, small, neighborhood favorite.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/CdKL_aWo3FggeQtTCmOYxQ/o.jpg"
  },
  {
    id: "ss-corner-shop-springs",
    name: "S&S Corner Shop",
    address: "11 Fort Pond Blvd, Springs, NY",
    town: "Springs",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-268-5711",
    lat: 41.032367,
    lng: -72.171207,
    hours: {
      mon: "8:00 AM - 4:00 PM",
      tue: "Closed",
      wed: "8:00 AM - 4:00 PM",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: null
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: ["pastries"],
    vibe: ["Brooklyn transplant feel"],
    knownFor: "Variety coffee, art books, local jewelry, no real seating (bench only)",
    description: "Brooklyn transplant feel (Fort Greene vibes), coffee + general store + vinyl/art books.",
    photo: "https://s3-media0.fl.yelpcdn.com/bphoto/u4KmETkPRun7f506J1LiZg/o.jpg"
  }
];

export default coffeeShops;
