// Long Island Coffee List — Shop Data
// No chains. Just real coffee.

const coffeeShops = [
  // ============================================================
  // WESTERN NASSAU / NYC-ADJACENT
  // ============================================================
  {
    id: "karak-house-great-neck",
    name: "Karak House Coffee Co",
    address: "12 Hicks Ln, Great Neck, NY",
    town: "Great Neck",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "646-570-2178",
    lat: 40.7870,
    lng: -73.7280,
    hours: {
      mon: "8:00 AM - 10:00 PM",
      tue: "8:00 AM - 10:00 PM",
      wed: "8:00 AM - 10:00 PM",
      thu: "8:00 AM - 10:00 PM",
      fri: "8:00 AM - 1:00 AM",
      sat: "10:00 AM - 1:00 AM",
      sun: "10:00 AM - 11:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["sweets", "biscoff cake", "chocolate chip cookies", "sticky coffee banana bread"],
    vibe: ["elegant", "open late", "chai-focused"],
    knownFor: "Spanish coffee latte, rose latte, Yemeni-style karak chai",
    description: "Elegant two-floor cafe, chai-focused, open late. Upstairs seating recommended.",
    photo: null
  },
  {
    id: "noir-bakery-great-neck",
    name: "NOIR Bakery & Cafe",
    address: "25 Cutter Mill Rd Unit 7, Great Neck, NY",
    town: "Great Neck",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-773-0973",
    lat: 40.7830,
    lng: -73.7210,
    hours: {
      mon: "7:00 AM - 3:00 PM",
      tue: "7:00 AM - 3:00 PM",
      wed: "7:00 AM - 3:00 PM",
      thu: "7:00 AM - 3:00 PM",
      fri: "7:00 AM - 3:00 PM",
      sat: "Closed",
      sun: "8:30 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["burekas", "shakshuka", "pastries", "breakfast"],
    vibe: ["petite", "warm"],
    knownFor: "Israeli street food + coffee",
    description: "Petite Israeli bakery/cafe with warm owners.",
    photo: null
  },
  {
    id: "bean-and-bean-douglaston",
    name: "Bean & Bean Queens — Roastery & Cafe",
    address: "252-29 Northern Blvd, Douglaston, NY",
    town: "Douglaston",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "347-235-0129",
    lat: 40.7685,
    lng: -73.7430,
    hours: {
      mon: "7:30 AM - 8:00 PM",
      tue: "7:30 AM - 8:00 PM",
      wed: "7:30 AM - 8:00 PM",
      thu: "7:30 AM - 8:00 PM",
      fri: "7:30 AM - 8:00 PM",
      sat: "7:30 AM - 8:00 PM",
      sun: "7:30 AM - 8:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: true, seating: "indoor" },
    food: ["sandwiches", "pastries"],
    vibe: ["spacious", "laptop-friendly", "loft-like"],
    knownFor: "On-site roasting, great remote work spot",
    description: "Spacious loft-like space with in-house roasting, popular for laptop work.",
    photo: null
  },
  {
    id: "for-five-manhasset",
    name: "For Five Coffee",
    address: "292 Plandome Rd, Manhasset, NY",
    town: "Manhasset",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-918-9488",
    lat: 40.7975,
    lng: -73.6990,
    hours: {
      mon: "7:00 AM - 7:00 PM",
      tue: "7:00 AM - 7:00 PM",
      wed: "7:00 AM - 7:00 PM",
      thu: "7:00 AM - 7:00 PM",
      fri: "7:00 AM - 7:00 PM",
      sat: "7:00 AM - 7:00 PM",
      sun: "7:00 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["eggs benedict on croissants", "Mexican grilled cheese", "full breakfast/lunch"],
    vibe: ["modern", "clean", "spacious", "laptop-friendly"],
    knownFor: "Quality espresso, matcha lattes",
    description: "Modern, clean, spacious. Good for working or catching up with friends.",
    photo: null
  },
  {
    id: "buttercooky-manhasset",
    name: "Buttercooky Bakery & Cafe",
    address: "140 Plandome Rd, Manhasset, NY",
    town: "Manhasset",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-627-1600",
    lat: 40.7960,
    lng: -73.7000,
    hours: {
      mon: "6:30 AM - 8:00 PM",
      tue: "6:30 AM - 8:00 PM",
      wed: "6:30 AM - 8:00 PM",
      thu: "6:30 AM - 8:00 PM",
      fri: "6:30 AM - 8:00 PM",
      sat: "6:30 AM - 8:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["full bakery", "pastries", "breakfast", "smoothies", "draft lattes"],
    vibe: ["country bakery", "local favorite"],
    knownFor: "Custom cakes, old-school bakery charm",
    description: "Country bakery feel, long-standing local favorite.",
    photo: null
  },
  {
    id: "taste-of-paris-floral-park",
    name: "Taste of Paris Coffeehouse",
    address: "83-52 Langdale St, Floral Park, NY",
    town: "Floral Park",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: null,
    lat: 40.7220,
    lng: -73.7040,
    hours: {
      mon: "7:00 AM - 8:00 PM",
      tue: "7:00 AM - 8:00 PM",
      wed: "7:00 AM - 8:00 PM",
      thu: "7:00 AM - 8:00 PM",
      fri: "7:00 AM - 10:00 PM",
      sat: "8:00 AM - 10:00 PM",
      sun: "8:00 AM - 8:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["quiet", "unique lighting"],
    knownFor: "Coconut banana latte, salted caramel latte, fun oversized cups",
    description: "Quiet local cafe with unique lighting. No photos on walls (owner preference).",
    photo: null
  },
  {
    id: "vida-coffee-franklin-square",
    name: "Vida Coffee Shop",
    address: "882 Hempstead Tpke, Franklin Square, NY",
    town: "Franklin Square",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: null,
    lat: 40.7075,
    lng: -73.6760,
    hours: {
      mon: "9:00 AM - 5:00 PM",
      tue: "9:00 AM - 5:00 PM",
      wed: "9:00 AM - 5:00 PM",
      thu: "9:00 AM - 5:00 PM",
      fri: "9:00 AM - 5:00 PM",
      sat: "9:00 AM - 5:00 PM",
      sun: "10:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["waffles", "tres leches cake", "empanadas", "paninis"],
    vibe: ["Latin family-owned", "peaceful"],
    knownFor: "Colombian cold brew, dulce de leche frappuccino",
    description: "Latin family-owned, peaceful, with plants and books to browse.",
    photo: null
  },
  {
    id: "ny-caffeine-franklin-square",
    name: "NY Caffeine",
    address: "797 Hempstead Tpke, Franklin Square, NY",
    town: "Franklin Square",
    region: "Nassau",
    subregion: "Western Nassau",
    phone: "516-216-1683",
    lat: 40.7080,
    lng: -73.6790,
    hours: {
      mon: "7:00 AM - 10:00 PM",
      tue: "7:00 AM - 10:00 PM",
      wed: "7:00 AM - 10:00 PM",
      thu: "7:00 AM - 10:00 PM",
      fri: "7:00 AM - 12:00 AM",
      sat: "7:00 AM - 12:00 AM",
      sun: "7:00 AM - 10:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: null, seating: "indoor+outdoor" },
    food: ["Dubai chocolate croissants", "savory croissants", "crepes", "pastries"],
    vibe: ["great decor", "heated outdoor tent", "open late"],
    knownFor: "Canned latte presentation, late hours",
    description: "Great decor, heated outdoor tent, unique drink presentation (canned lattes).",
    photo: null
  },

  // ============================================================
  // CENTRAL NASSAU
  // ============================================================
  {
    id: "cafe-blessing-mineola",
    name: "Cafe Blessing",
    address: "47 Mineola Blvd, Mineola, NY",
    town: "Mineola",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-248-2169",
    lat: 40.7490,
    lng: -73.6400,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "8:30 AM - 3:00 PM",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["Korean snacks", "scallion bread", "bulgogi", "banana loaf", "fresh-cut fruit drinks"],
    vibe: ["tiny", "cozy", "Korean-owned"],
    knownFor: "Chagaccino, strawberry matcha with fresh fruit, in-house roasting",
    description: "Tiny, cozy Korean-owned cafe that roasts their own beans.",
    photo: null
  },
  {
    id: "east-rock-garden-city",
    name: "East Rock Coffee",
    address: "653 Franklin Ave, Garden City, NY",
    town: "Garden City",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-280-2429",
    lat: 40.7268,
    lng: -73.6340,
    hours: {
      mon: "8:30 AM - 6:00 PM",
      tue: "8:30 AM - 6:00 PM",
      wed: "8:30 AM - 6:00 PM",
      thu: "8:30 AM - 6:00 PM",
      fri: "8:30 AM - 6:00 PM",
      sat: "8:30 AM - 6:00 PM",
      sun: "8:30 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["quesadillas", "French toast", "omelets", "full brunch menu"],
    vibe: ["warm", "colorful", "Instagram-viral"],
    knownFor: "Brunch destination, London fog, espresso drinks",
    description: "Warm, colorful, unique decor with a huge local following (viral on Instagram).",
    photo: null
  },
  {
    id: "for-five-garden-city",
    name: "For Five Coffee",
    address: "147 7th St, Garden City, NY",
    town: "Garden City",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-271-9100",
    lat: 40.7260,
    lng: -73.6380,
    hours: {
      mon: "7:00 AM - 8:30 PM",
      tue: "7:00 AM - 8:30 PM",
      wed: "7:00 AM - 8:30 PM",
      thu: "7:00 AM - 8:30 PM",
      fri: "7:00 AM - 8:30 PM",
      sat: "7:00 AM - 8:30 PM",
      sun: "7:00 AM - 8:30 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: true, seating: "indoor" },
    food: ["full menu", "pastries", "grab-and-go"],
    vibe: ["open concept", "well-lit", "laptop-friendly"],
    knownFor: "Good workspace, house-roasted coffee",
    description: "Open concept, well-lit, popular laptop/work spot.",
    photo: null
  },
  {
    id: "oak-and-orange-mineola",
    name: "Oak & Orange",
    address: "91 Mineola Blvd, Mineola, NY",
    town: "Mineola",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-746-3809",
    lat: 40.7495,
    lng: -73.6390,
    hours: {
      mon: "8:00 AM - 3:00 PM",
      tue: "8:00 AM - 3:00 PM",
      wed: "8:00 AM - 3:00 PM",
      thu: "8:00 AM - 3:00 PM",
      fri: "8:00 AM - 3:00 PM",
      sat: "Closed",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["Japanese egg sando", "grilled cheese with tomato bisque", "artisanal sandwiches"],
    vibe: ["elevated", "curated", "relaxing"],
    knownFor: "Unique menu, beautiful interior, great lunch spot",
    description: "Elevated, curated, relaxing. Near the train station.",
    photo: null
  },
  {
    id: "qahwah-house-westbury",
    name: "Qahwah House",
    address: "541 Old Country Rd, Westbury, NY",
    town: "Westbury",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-214-6143",
    lat: 40.7560,
    lng: -73.5900,
    hours: {
      mon: "8:00 AM - 11:00 PM",
      tue: "8:00 AM - 11:00 PM",
      wed: "8:00 AM - 11:00 PM",
      thu: "8:00 AM - 11:00 PM",
      fri: "8:00 AM - 1:00 AM",
      sat: "8:00 AM - 1:00 AM",
      sun: "8:00 AM - 11:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: true, seating: "indoor" },
    food: ["Yemeni pastries", "Khaliat Alnahi (honeycomb)", "desserts"],
    vibe: ["lively", "community hangout", "open late"],
    knownFor: "Yemeni coffee imported from Yemen, roasted in-house, late hours",
    description: "Large, lively Yemeni coffee house. Social/community hangout.",
    photo: null
  },
  {
    id: "ny-caffeine-westbury",
    name: "NY Caffeine",
    address: "1540 Old Country Rd, Westbury, NY",
    town: "Westbury",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: null,
    lat: 40.7550,
    lng: -73.5700,
    hours: {
      mon: "7:00 AM - 10:00 PM",
      tue: "7:00 AM - 10:00 PM",
      wed: "7:00 AM - 10:00 PM",
      thu: "7:00 AM - 10:00 PM",
      fri: "7:00 AM - 12:00 AM",
      sat: "7:00 AM - 12:00 AM",
      sun: "7:00 AM - 10:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["pastries", "seasonal treats"],
    vibe: ["beautiful", "cozy", "outdoor seating"],
    knownFor: "Canned latte presentation, seasonal specials",
    description: "Beautiful, cozy, with outdoor seating area.",
    photo: null
  },
  {
    id: "early-bird-east-meadow",
    name: "The Early Bird Cafe",
    address: "1934a Hempstead Tpke, East Meadow, NY",
    town: "East Meadow",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-916-3884",
    lat: 40.7140,
    lng: -73.5590,
    hours: {
      mon: "Closed",
      tue: "8:00 AM - 7:00 PM",
      wed: "8:00 AM - 7:00 PM",
      thu: "8:00 AM - 7:00 PM",
      fri: "8:00 AM - 7:00 PM",
      sat: "8:00 AM - 7:00 PM",
      sun: "8:00 AM - 7:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avocado toast", "fried egg sandwiches", "ciabatta sandwiches"],
    vibe: ["cozy", "welcoming", "laptop-friendly"],
    knownFor: "Best mocha latte on LI (per regulars), great brunch",
    description: "Cozy, welcoming, great for working.",
    photo: null
  },
  {
    id: "grami-caffe-malverne",
    name: "GRAMI CAFFE",
    address: "22A Church St, Malverne, NY",
    town: "Malverne",
    region: "Nassau",
    subregion: "Central Nassau",
    phone: "516-788-0385",
    lat: 40.6720,
    lng: -73.6740,
    hours: {
      mon: "6:00 AM - 7:00 PM",
      tue: "6:00 AM - 7:00 PM",
      wed: "6:00 AM - 7:00 PM",
      thu: "6:00 AM - 7:00 PM",
      fri: "6:00 AM - 7:00 PM",
      sat: "7:00 AM - 7:00 PM",
      sun: "7:00 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["vegan spanakopita", "pastries"],
    vibe: ["Greek/Mediterranean", "family-owned", "warm hospitality"],
    knownFor: "Freddo espresso (hard to find on LI), locally roasted beans",
    description: "Greek/Mediterranean family-owned, warm hospitality, real ceramic cups.",
    photo: null
  },

  // ============================================================
  // NORTH SHORE NASSAU
  // ============================================================
  {
    id: "sweet-harbor-roslyn",
    name: "Sweet Harbor Coffee",
    address: "1353 Old Northern Blvd, Roslyn, NY",
    town: "Roslyn",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.7998,
    lng: -73.6510,
    hours: {
      mon: "Closed",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "chocolate croissants"],
    vibe: ["Brooklyn-inspired", "cozy"],
    knownFor: "Iced salted caramel latte, matcha vanilla rose latte",
    description: "Brooklyn-inspired, cozy, limited seating but popular.",
    photo: null
  },
  {
    id: "dianes-bakery-roslyn",
    name: "Diane's Bakery/Cafe",
    address: "23 Bryant Ave, Roslyn, NY",
    town: "Roslyn",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-621-2522",
    lat: 40.8000,
    lng: -73.6485,
    hours: {
      mon: "Closed",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["quiche", "pies", "cakes", "salad bar", "pasta"],
    vibe: ["charming", "garden seating", "elevated"],
    knownFor: "Best quiche on LI, gorgeous patio",
    description: "Charming garden seating, bustling, elevated cafe.",
    photo: null
  },
  {
    id: "17a-cafe-roslyn-heights",
    name: "17A Cafe",
    address: "17A Lincoln Ave, Roslyn Heights, NY",
    town: "Roslyn Heights",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-626-0510",
    lat: 40.7870,
    lng: -73.6475,
    hours: {
      mon: "9:00 AM - 5:00 PM",
      tue: "Closed",
      wed: "Closed",
      thu: "Closed",
      fri: "Closed",
      sat: "Closed",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["smoked salmon bagels", "acai bowls", "vegan/GF options", "fresh juices"],
    vibe: ["hidden gem", "owner-operated"],
    knownFor: "Off-menu items, incredible personal service, lobster salad",
    description: "Tiny hidden gem, owner-operated by 'Scotty Bagel'. Monday only — check ahead!",
    photo: null
  },
  {
    id: "southdown-glen-cove",
    name: "Southdown Coffee",
    address: "149 Glen St Suite 2, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.8625,
    lng: -73.6340,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avocado toast", "grilled cheese avo pesto", "scones", "baked goods"],
    vibe: ["bright", "relaxing"],
    knownFor: "House-roasted beans, consistently excellent across all locations",
    description: "Bright, relaxing, warm staff. Local roaster with multiple LI locations.",
    photo: null
  },
  {
    id: "southdown-oyster-bay",
    name: "Southdown Coffee",
    address: "49 Audrey Ave, Oyster Bay, NY",
    town: "Oyster Bay",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.8710,
    lng: -73.5320,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avo pesto grilled cheese", "banana bread (nut free)", "cornbread"],
    vibe: ["cute", "classic", "cozy seaside"],
    knownFor: "Lavender latte (house-made syrup), olive oil cake",
    description: "Cute, classic, cozy seaside town cafe. Limited seating (worth the wait).",
    photo: null
  },
  {
    id: "cafe-nicos-glen-cove",
    name: "Cafe Nico's",
    address: "221 Glen St B, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-671-1444",
    lat: 40.8623,
    lng: -73.6330,
    hours: {
      mon: null,
      tue: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      sun: null
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["gelato", "Italian pastries", "espresso"],
    vibe: ["old-school Little Italy", "cash only"],
    knownFor: "Authentic Italian espresso, boxing glove decor, cash only",
    description: "Old-school Little Italy feel. Cash only!",
    photo: null
  },
  {
    id: "ready-coffee-glen-cove",
    name: "Ready Coffee",
    address: "96 Forest Ave, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: null,
    lat: 40.8620,
    lng: -73.6290,
    hours: {
      mon: "5:00 AM - 9:00 PM",
      tue: "5:00 AM - 9:00 PM",
      wed: "5:00 AM - 9:00 PM",
      thu: "5:00 AM - 9:00 PM",
      fri: "5:00 AM - 9:00 PM",
      sat: "5:00 AM - 9:00 PM",
      sun: "5:00 AM - 9:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: [],
    vibe: ["drive-thru only", "fast"],
    knownFor: "Sugar-free options (diabetic friendly), fast drive-thru service",
    description: "Drive-thru only, two lanes, fast and friendly.",
    photo: null
  },
  {
    id: "sea-cliff-daily-grind",
    name: "Sea Cliff Daily Grind",
    address: "230 Sea Cliff Ave, Sea Cliff, NY",
    town: "Sea Cliff",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-675-1187",
    lat: 40.8490,
    lng: -73.6450,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["vegan options", "lettuce wraps", "biscuits"],
    vibe: ["casual"],
    knownFor: "Daily vegan specials (ask the counter)",
    description: "Casual cafe with daily vegan specials.",
    photo: null
  },
  {
    id: "dessertino-sea-cliff",
    name: "Dessertino - The Crafty Spoon",
    address: "227 Glen Cove Ave, Sea Cliff, NY",
    town: "Sea Cliff",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-817-9421",
    lat: 40.8480,
    lng: -73.6440,
    hours: {
      mon: "10:00 AM - 9:30 PM",
      tue: "10:00 AM - 9:30 PM",
      wed: "10:00 AM - 9:30 PM",
      thu: "10:00 AM - 9:30 PM",
      fri: "10:00 AM - 10:30 PM",
      sat: "10:00 AM - 10:30 PM",
      sun: "10:00 AM - 9:30 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["Italian desserts", "Greek desserts", "Asian-inspired desserts", "gelato", "kebabs"],
    vibe: ["warm", "artsy", "book-friendly"],
    knownFor: "Pistachio tiramisu, multi-cultural dessert menu",
    description: "Warm, artsy, book-friendly. Great for reading.",
    photo: null
  },
  {
    id: "st-roccos-glen-cove",
    name: "St. Rocco's Bakery",
    address: "4 St Rocco Pl, Glen Cove, NY",
    town: "Glen Cove",
    region: "Nassau",
    subregion: "North Shore Nassau",
    phone: "516-427-5333",
    lat: 40.8630,
    lng: -73.6350,
    hours: {
      mon: "7:00 AM - 7:00 PM",
      tue: "7:00 AM - 7:00 PM",
      wed: "7:00 AM - 7:00 PM",
      thu: "7:00 AM - 7:00 PM",
      fri: "7:00 AM - 7:00 PM",
      sat: "7:00 AM - 7:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["croissants", "cheesecake", "eclairs", "semolina bread", "cappuccinos"],
    vibe: ["legendary Italian bakery"],
    knownFor: "Best Italian bakery on Long Island (per many locals)",
    description: "Legendary Italian bakery, can have long holiday lines.",
    photo: null
  },

  // ============================================================
  // SOUTH SHORE NASSAU
  // ============================================================
  {
    id: "space-cowboy-long-beach",
    name: "Space Cowboy Coffee Co",
    address: "511 Long Beach Blvd, Long Beach, NY",
    town: "Long Beach",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-544-1665",
    lat: 40.5884,
    lng: -73.6579,
    hours: {
      mon: "6:00 AM - 4:00 PM",
      tue: "6:00 AM - 4:00 PM",
      wed: "6:00 AM - 4:00 PM",
      thu: "6:00 AM - 4:00 PM",
      fri: "6:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 1:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["light bites"],
    vibe: ["artsy", "beachy"],
    knownFor: "Cherry lemonade, salty sap iced latte, cool vibes",
    description: "Artsy, beachy, great artwork on walls.",
    photo: null
  },
  {
    id: "long-beach-coffee-tee",
    name: "Long Beach Coffee & Tee",
    address: "220 W Park Ave, Long Beach, NY",
    town: "Long Beach",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-608-9333",
    lat: 40.5890,
    lng: -73.6620,
    hours: {
      mon: "8:00 AM - 11:00 PM",
      tue: "8:00 AM - 11:00 PM",
      wed: "8:00 AM - 11:00 PM",
      thu: "8:00 AM - 11:00 PM",
      fri: "8:00 AM - 12:00 AM",
      sat: "8:00 AM - 12:00 AM",
      sun: "8:00 AM - 9:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "desserts"],
    vibe: ["unique", "golf simulator", "open late"],
    knownFor: "Golf simulators you can rent, good evening hangout",
    description: "Coffee shop + golf simulator combo!",
    photo: null
  },
  {
    id: "no-rush-freeport",
    name: "No Rush Cafe",
    address: "399 S Main St, Freeport, NY",
    town: "Freeport",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-262-3289",
    lat: 40.6530,
    lng: -73.5830,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 6:30 PM",
      wed: "7:00 AM - 6:30 PM",
      thu: "7:00 AM - 6:30 PM",
      fri: "7:00 AM - 6:30 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: true, outlets: null, seating: "indoor" },
    food: ["BEC on croissant", "cinnamon rolls (homemade)", "baked goods"],
    vibe: ["cozy", "living-room feel", "kid-friendly"],
    knownFor: "Biscoff latte, sugar cookie latte, cozy 'no rush' atmosphere",
    description: "Cozy living-room feel, games for kids, books.",
    photo: null
  },
  {
    id: "ready-coffee-freeport",
    name: "Ready Coffee",
    address: "177 Atlantic Ave, Freeport, NY",
    town: "Freeport",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: null,
    lat: 40.6500,
    lng: -73.5780,
    hours: {
      mon: "5:00 AM - 6:00 PM",
      tue: "5:00 AM - 6:00 PM",
      wed: "5:00 AM - 6:00 PM",
      thu: "5:00 AM - 6:00 PM",
      fri: "5:00 AM - 6:00 PM",
      sat: "5:00 AM - 6:00 PM",
      sun: "5:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: [],
    vibe: ["drive-thru", "fast service"],
    knownFor: "Shakes, customizable drinks, friendly staff",
    description: "Drive-thru, fast service.",
    photo: null
  },
  {
    id: "rs-beanery-merrick",
    name: "RS Beanery",
    address: "153 Merrick Ave, Merrick, NY",
    town: "Merrick",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-208-7887",
    lat: 40.6632,
    lng: -73.5510,
    hours: {
      mon: "8:00 AM - 12:30 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: [],
    vibe: ["comfy", "cozy"],
    knownFor: "Signature iced lattes, Friday evening hours",
    description: "Comfy, cozy, great atmosphere.",
    photo: null
  },
  {
    id: "hard-bean-merrick",
    name: "Hard Bean",
    address: "15 Merrick Ave, Merrick, NY",
    town: "Merrick",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "631-304-6647",
    lat: 40.6640,
    lng: -73.5520,
    hours: {
      mon: "6:00 AM - 6:00 PM",
      tue: "6:00 AM - 6:00 PM",
      wed: "6:00 AM - 6:00 PM",
      thu: "6:00 AM - 6:00 PM",
      fri: "6:00 AM - 6:00 PM",
      sat: "8:00 AM - 6:00 PM",
      sun: "8:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["breakfast sandwiches", "lunch sandwiches", "croissants"],
    vibe: ["crisp", "clean", "intentional decor"],
    knownFor: "Cookie butter shaken espresso, tiramisu latte, matcha",
    description: "Crisp, clean, intentional decor, coffee bean scent, gentle music.",
    photo: null
  },
  {
    id: "coffee-barn-merrick",
    name: "Coffee Barn",
    address: "2081 Merrick Rd, Merrick, NY",
    town: "Merrick",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-517-2154",
    lat: 40.6550,
    lng: -73.5490,
    hours: {
      mon: "6:00 AM - 9:00 PM",
      tue: "6:00 AM - 9:00 PM",
      wed: "6:00 AM - 9:00 PM",
      thu: "6:00 AM - 9:00 PM",
      fri: "6:00 AM - 9:00 PM",
      sat: "6:00 AM - 9:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: ["seasonal donuts"],
    vibe: ["drive-thru", "seasonal/themed", "TikTok famous"],
    knownFor: "Pumpkin lattes served in real pumpkins, Instagram/TikTok aesthetic",
    description: "Drive-thru barn, heavily seasonal/themed (TikTok famous).",
    photo: null
  },
  {
    id: "pink-cafe-rockville-centre",
    name: "The Pink Cafe & Bakery",
    address: "24 N Park Ave, Rockville Centre, NY",
    town: "Rockville Centre",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-344-5340",
    lat: 40.6588,
    lng: -73.6413,
    hours: {
      mon: "12:00 PM - 8:00 PM",
      tue: "10:00 AM - 8:00 PM",
      wed: "10:00 AM - 8:00 PM",
      thu: "10:00 AM - 8:00 PM",
      fri: "10:00 AM - 8:00 PM",
      sat: "10:00 AM - 8:00 PM",
      sun: "10:00 AM - 8:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["baked in-house daily", "biscoff cookies"],
    vibe: ["pink-themed", "cute", "party-friendly"],
    knownFor: "Oatmilk vanilla matcha latte, tea parties, Bridgerton vibes",
    description: "Pink-themed, cute, great for girls' events/parties.",
    photo: null
  },
  {
    id: "flour-shoppe-rockville-centre",
    name: "The Flour Shoppe Cafe",
    address: "41 S Park Ave, Rockville Centre, NY",
    town: "Rockville Centre",
    region: "Nassau",
    subregion: "South Shore Nassau",
    phone: "516-442-1299",
    lat: 40.6585,
    lng: -73.6410,
    hours: {
      mon: "8:00 AM - 2:00 PM",
      tue: "8:00 AM - 2:00 PM",
      wed: "8:00 AM - 2:00 PM",
      thu: "8:00 AM - 2:00 PM",
      fri: "8:00 AM - 2:00 PM",
      sat: "8:00 AM - 2:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["full brunch menu", "homemade chips", "cannoli cookies"],
    vibe: ["elevated brunch", "outdoor area"],
    knownFor: "Honey lavender latte, brunch spot",
    description: "Elevated brunch cafe with a nice outdoor area.",
    photo: null
  },

  // ============================================================
  // WESTERN SUFFOLK
  // ============================================================
  {
    id: "beehive-huntington",
    name: "Beehive Espresso Bar",
    address: "176 New York Ave, Huntington, NY",
    town: "Huntington",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-546-8070",
    lat: 40.8685,
    lng: -73.4265,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "8:00 AM - 7:00 PM",
      sun: "8:00 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["baklava", "almond croissants", "pastries", "gelato"],
    vibe: ["warm", "honeycomb decor", "intentional"],
    knownFor: "Intentional specialty coffee, latte art, Turkish baklava",
    description: "Warm yellow honeycomb decor, sofas + easy chairs, real dishes (not disposable), next to Heckscher Park.",
    photo: null
  },
  {
    id: "special-cup-huntington",
    name: "The Special Cup",
    address: "387 New York Ave, Huntington, NY",
    town: "Huntington",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-470-4697",
    lat: 40.8690,
    lng: -73.4250,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["full breakfast/lunch", "avocado toast", "baked goods"],
    vibe: ["artsy", "homey", "vibey music"],
    knownFor: "Exhaustive flavored latte list, great brunch, formerly 'Soul Brew'",
    description: "Artsy, homey, vibey music. Good for working or socializing.",
    photo: null
  },
  {
    id: "southdown-huntington",
    name: "Southdown Coffee",
    address: "210 Wall St Unit B, Huntington, NY",
    town: "Huntington",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.8682,
    lng: -73.4257,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["famous egg sandwich", "pastries", "scones"],
    vibe: ["bright", "clean"],
    knownFor: "House-roasted coffee, the egg sandwich",
    description: "Bright, clean, narrow but inviting. House-made syrups.",
    photo: null
  },
  {
    id: "nautilus-huntington-station",
    name: "Nautilus Roasting Co",
    address: "1000 New York Ave Unit A, Huntington Station, NY",
    town: "Huntington Station",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.8534,
    lng: -73.4115,
    hours: {
      mon: "6:30 AM - 4:00 PM",
      tue: "6:30 AM - 4:00 PM",
      wed: "6:30 AM - 4:00 PM",
      thu: "6:30 AM - 4:00 PM",
      fri: "6:30 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: "plenty", seating: "indoor" },
    food: ["vegan breakfast burritos", "whoopie pies", "GF macarons"],
    vibe: ["eclectic", "vegan", "community events"],
    knownFor: "Vegan coffee house, community events (open mic, run club, markets), in-house roasting",
    description: "Victorian living room meets eclectic art — weird and awesome. Vegan cafe. Lots of outlets.",
    photo: null
  },
  {
    id: "brewology-huntington-station",
    name: "Brewology Coffee",
    address: "556 E Jericho Tpke, Huntington Station, NY",
    town: "Huntington Station",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-470-3960",
    lat: 40.8540,
    lng: -73.4050,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: "some", seating: "indoor" },
    food: ["cookies", "seasonal pastries"],
    vibe: ["cute", "fun", "grab-and-go"],
    knownFor: "Chagaccino, strawberry matcha, seasonal specials",
    description: "Cute, fun, music a bit loud. More grab-and-go than sit-and-work.",
    photo: null
  },
  {
    id: "cold-spring-harbor-cafe",
    name: "Cold Spring Harbor Cafe",
    address: "85 Main St, Cold Spring Harbor, NY",
    town: "Cold Spring Harbor",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.8715,
    lng: -73.4568,
    hours: {
      mon: "7:15 AM - 5:00 PM",
      tue: "7:15 AM - 5:00 PM",
      wed: "7:15 AM - 5:00 PM",
      thu: "7:15 AM - 5:00 PM",
      fri: "7:15 AM - 5:00 PM",
      sat: "7:15 AM - 5:00 PM",
      sun: "7:15 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["small", "locally owned", "kid-friendly"],
    knownFor: "Cinnamon toast crunch latte, seasonal pumpkin/snowman cups",
    description: "Small, locally owned, kid-friendly, fresh-paint-new feel.",
    photo: null
  },
  {
    id: "sweetie-pies-cold-spring-harbor",
    name: "Sweetie Pies on Main",
    address: "181 Main St, Cold Spring Harbor, NY",
    town: "Cold Spring Harbor",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-367-9500",
    lat: 40.8720,
    lng: -73.4580,
    hours: {
      mon: "7:30 AM - 4:00 PM",
      tue: "7:30 AM - 4:00 PM",
      wed: "7:30 AM - 4:00 PM",
      thu: "7:30 AM - 4:00 PM",
      fri: "7:30 AM - 4:00 PM",
      sat: "7:30 AM - 5:00 PM",
      sun: "7:30 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["pastries", "cookies", "chocolate danish", "caramel macchiatos"],
    vibe: ["quaint", "New England charm", "dog-friendly garden"],
    knownFor: "Adorable aesthetic, great post-hike stop",
    description: "Quaint, New England charm, dog-friendly garden, indoor + outdoor seating.",
    photo: null
  },
  {
    id: "gourmet-whaler-cold-spring-harbor",
    name: "The Gourmet Whaler",
    address: "111 Main St, Cold Spring Harbor, NY",
    town: "Cold Spring Harbor",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-659-2977",
    lat: 40.8718,
    lng: -73.4570,
    hours: {
      mon: "8:00 AM - 4:00 PM",
      tue: "8:00 AM - 4:00 PM",
      wed: "Closed",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["shrimp tacos", "quinoa bowls", "wraps", "ice cream", "baked goods"],
    vibe: ["multi-concept"],
    knownFor: "Multi-concept (bakery + ice cream + cafe + lunch), Nutella latte",
    description: "Multi-concept: bakery + ice cream + cafe + lunch.",
    photo: null
  },
  {
    id: "southdown-northport",
    name: "Southdown Coffee",
    address: "72 Main St, Northport, NY",
    town: "Northport",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.9009,
    lng: -73.3434,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "scones", "zucchini bread"],
    vibe: ["cute", "local", "Main Street charm"],
    knownFor: "Consistent Southdown quality, apple crumb",
    description: "Cute, local, Main Street charm.",
    photo: null
  },
  {
    id: "the-barn-east-northport",
    name: "The Barn",
    address: "430 Larkfield Rd, East Northport, NY",
    town: "East Northport",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: null,
    lat: 40.8768,
    lng: -73.3243,
    hours: {
      mon: "8:00 AM - 6:00 PM",
      tue: "8:00 AM - 6:00 PM",
      wed: "8:00 AM - 6:00 PM",
      thu: "8:00 AM - 6:00 PM",
      fri: "8:00 AM - 6:00 PM",
      sat: "8:00 AM - 6:00 PM",
      sun: "8:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: [],
    vibe: ["Instagram-famous", "seasonal", "drive-thru"],
    knownFor: "Pumpkin spice latte in a real pumpkin, holiday themed drinks",
    description: "Instagram-famous seasonal drinks, drive-thru concept.",
    photo: null
  },
  {
    id: "babylon-bean-babylon",
    name: "Babylon Bean Coffee House",
    address: "17 Fire Island Ave, Babylon, NY",
    town: "Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-587-7729",
    lat: 40.6956,
    lng: -73.3257,
    hours: {
      mon: "4:45 AM - 7:00 PM",
      tue: "4:45 AM - 7:00 PM",
      wed: "4:45 AM - 7:00 PM",
      thu: "4:45 AM - 7:00 PM",
      fri: "4:45 AM - 9:00 PM",
      sat: "4:45 AM - 9:00 PM",
      sun: "5:45 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["bagels", "pastries", "seasonal drinks"],
    vibe: ["art gallery", "old school architecture", "cozy"],
    knownFor: "Cold brew display, opens insanely early (4:45am!), art gallery space",
    description: "Art gallery + coffee house, old school architecture, cozy but can feel cramped.",
    photo: null
  },
  {
    id: "jack-jacks-babylon",
    name: "Jack Jack's Coffee House",
    address: "223 Deer Park Ave, Babylon, NY",
    town: "Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-885-3722",
    lat: 40.6960,
    lng: -73.3270,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 12:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["all-day egg sandwich", "salads", "sandwiches", "magic cookie bars"],
    vibe: ["art gallery", "dog-friendly"],
    knownFor: "Homemade mocha/caramel sauces, local art, all-day egg sandwich",
    description: "Art gallery meets coffee shop, dog-friendly.",
    photo: null
  },
  {
    id: "sergi-west-babylon",
    name: "Sergi Coffee Roaster",
    address: "780 Sunrise Hwy, West Babylon, NY",
    town: "West Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-539-8006",
    lat: 40.7179,
    lng: -73.3590,
    hours: {
      mon: "Closed",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "9:00 AM - 2:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "sandwiches", "Turkish coffee"],
    vibe: ["roastery"],
    knownFor: "In-house roasting, great value espresso ($3.35 double espresso!)",
    description: "In-house roasting with great value espresso.",
    photo: null
  },
  {
    id: "north-babylon-bean",
    name: "North Babylon Bean Coffee House",
    address: "775 Deer Pk Rd, North Babylon, NY",
    town: "North Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-314-4073",
    lat: 40.7326,
    lng: -73.3215,
    hours: {
      mon: "5:00 AM - 4:00 PM",
      tue: "5:00 AM - 4:00 PM",
      wed: "5:00 AM - 4:00 PM",
      thu: "5:00 AM - 4:00 PM",
      fri: "5:00 AM - 4:00 PM",
      sat: "5:00 AM - 4:00 PM",
      sun: "6:00 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["avocado toast", "pastries", "breakfast items"],
    vibe: ["friendly owner", "community"],
    knownFor: "Vietnamese iced coffee, hazelnut brewed from bean, roasts on-site",
    description: "Friendly owner (Ryan) who knows everyone by name. Brewing visible in back.",
    photo: null
  },
  {
    id: "east-end-roasters-north-babylon",
    name: "East End Coffee Roasters",
    address: "775 Deer Park Ave, North Babylon, NY",
    town: "North Babylon",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-400-6699",
    lat: 40.7330,
    lng: -73.3220,
    hours: {
      mon: "6:30 AM - 3:30 PM",
      tue: "6:30 AM - 3:30 PM",
      wed: "6:30 AM - 3:30 PM",
      thu: "6:30 AM - 3:30 PM",
      fri: "6:30 AM - 3:30 PM",
      sat: "7:00 AM - 2:00 PM",
      sun: "7:00 AM - 1:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: [],
    vibe: ["roastery"],
    knownFor: "Whole bean roaster, ships nationwide, house blends",
    description: "Whole bean roaster that ships nationwide.",
    photo: null
  },
  {
    id: "so-sveglio-lindenhurst",
    name: "So Sveglio Espresso Bar",
    address: "124 S Wellwood Ave, Lindenhurst, NY",
    town: "Lindenhurst",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-412-3750",
    lat: 40.6868,
    lng: -73.3735,
    hours: {
      mon: "9:00 AM - 6:00 PM",
      tue: "8:00 AM - 6:00 PM",
      wed: "8:00 AM - 6:00 PM",
      thu: "8:00 AM - 6:00 PM",
      fri: "8:00 AM - 6:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "10:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["gelato", "cannolis", "Italian pastries"],
    vibe: ["Italian espresso bar"],
    knownFor: "Italian espresso bar, gelato catering for events",
    description: "Italian espresso bar with gelato catering for events.",
    photo: null
  },
  {
    id: "munis-lindenhurst",
    name: "Muni's Coffee Joint",
    address: "222 N Wellwood Ave, Lindenhurst, NY",
    town: "Lindenhurst",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-412-5085",
    lat: 40.6880,
    lng: -73.3740,
    hours: {
      mon: "6:00 AM - 4:00 PM",
      tue: "6:00 AM - 4:00 PM",
      wed: "6:00 AM - 4:00 PM",
      thu: "6:00 AM - 4:00 PM",
      fri: "6:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["egg sandwiches", "muffins", "vegan options"],
    vibe: ["Brazilian vibes", "cozy", "trendy", "kid-friendly"],
    knownFor: "Great iced coffee, chill atmosphere, live music vibes",
    description: "Brazilian vibes, cozy, trendy, books + toys for kids.",
    photo: null
  },
  {
    id: "milano-bean-bay-shore",
    name: "Milano Bean Cafe",
    address: "6 E Main St, Bay Shore, NY",
    town: "Bay Shore",
    region: "Suffolk",
    subregion: "Western Suffolk",
    phone: "631-328-1529",
    lat: 40.7254,
    lng: -73.2454,
    hours: {
      mon: "7:00 AM - 10:00 PM",
      tue: "7:00 AM - 10:00 PM",
      wed: "7:00 AM - 10:00 PM",
      thu: "7:00 AM - 10:00 PM",
      fri: "7:00 AM - 11:00 PM",
      sat: "7:00 AM - 11:00 PM",
      sun: "7:00 AM - 10:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["baked goods", "light fare"],
    vibe: ["community hangout", "comfy sofas", "open late"],
    knownFor: "Fruity pebble matcha, strawberry cheesecake latte, late hours",
    description: "Community hangout — people off phones, studying or socializing. Comfy sofas.",
    photo: null
  },

  // ============================================================
  // CENTRAL/EASTERN SUFFOLK
  // ============================================================
  {
    id: "my-towns-cafe-east-islip",
    name: "My Town's Cafe",
    address: "51 W Main St, East Islip, NY",
    town: "East Islip",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-446-4089",
    lat: 40.7321,
    lng: -73.1856,
    hours: {
      mon: "9:00 AM - 9:00 PM",
      tue: "6:00 AM - 9:00 PM",
      wed: "6:00 AM - 9:00 PM",
      thu: "6:00 AM - 9:00 PM",
      fri: "6:00 AM - 9:00 PM",
      sat: "7:00 AM - 9:00 PM",
      sun: "7:00 AM - 8:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: null, seating: "indoor" },
    food: ["quiche", "chocolate croissants", "tiramisu", "ciabatta sandwiches"],
    vibe: ["rustic", "string lights", "Instagram-worthy"],
    knownFor: "Cinnamon bun foam lattes, Irish cream cold brew, Instagram-worthy decor",
    description: "Rustic dark wood, string lights, husband-and-wife owned.",
    photo: null
  },
  {
    id: "dark-horse-sayville",
    name: "Dark Horse Coffee & Kitchen",
    address: "4836 Sunrise Hwy, Sayville, NY",
    town: "Sayville",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-256-6988",
    lat: 40.7351,
    lng: -73.0822,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "8:00 AM - 2:00 PM",
      sun: "8:00 AM - 2:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["chorizo & fontina burrito", "avocado toasts", "breakfast items"],
    vibe: ["warm", "no rush", "health-forward"],
    knownFor: "Shaken honey espresso, shroom latte, German tourists rave about it",
    description: "Warm, music + books in background, 7 tables, no rush.",
    photo: null
  },
  {
    id: "sayville-bean",
    name: "Sayville Bean Coffee House",
    address: "59 W Main St, Sayville, NY",
    town: "Sayville",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-319-5637",
    lat: 40.7355,
    lng: -73.0830,
    hours: {
      mon: "5:00 AM - 7:30 PM",
      tue: "5:00 AM - 7:30 PM",
      wed: "5:00 AM - 7:30 PM",
      thu: "5:00 AM - 7:30 PM",
      fri: "5:00 AM - 7:30 PM",
      sat: "5:00 AM - 7:30 PM",
      sun: "5:30 AM - 7:00 PM"
    },
    amenities: { wifi: null, bathroom: true, outlets: null, seating: "indoor" },
    food: ["wraps", "smoothies", "hot chocolate", "breakfast sandwiches"],
    vibe: ["classic community coffee house", "live music"],
    knownFor: "Live music, cold brew production visible on-site, early hours",
    description: "Classic community coffee house.",
    photo: null
  },
  {
    id: "brownstones-sayville",
    name: "Brownstones Coffee Sayville",
    address: "229 W Main St, Sayville, NY",
    town: "Sayville",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-567-5376",
    lat: 40.7345,
    lng: -73.0850,
    hours: {
      mon: "7:30 AM - 3:00 PM",
      tue: "7:30 AM - 3:00 PM",
      wed: "7:30 AM - 3:00 PM",
      thu: "7:30 AM - 3:00 PM",
      fri: "7:30 AM - 3:30 PM",
      sat: "7:30 AM - 3:30 PM",
      sun: "7:30 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["frittata", "pancakes", "Cobb salad", "espresso martinis"],
    vibe: ["cute", "quaint", "brunch spot"],
    knownFor: "Gourmet brunch, themed drinks, mimosas",
    description: "Cute, quaint brunch spot.",
    photo: null
  },
  {
    id: "kings-coast-bohemia",
    name: "Kings Coast Coffee Company",
    address: "55 Carlough Rd, Bohemia, NY",
    town: "Bohemia",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-238-1666",
    lat: 40.7693,
    lng: -73.1148,
    hours: {
      mon: "8:00 AM - 5:00 PM",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "9:00 AM - 4:00 PM",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: [],
    vibe: ["industrial park", "serious coffee", "roastery"],
    knownFor: "In-house roasting, 4-shot large lattes, Bowbreaker roast, Lifeline espresso",
    description: "Hidden in an industrial park, roastery visible through glass. Serious coffee.",
    photo: null
  },
  {
    id: "coho-patchogue",
    name: "CoHo Coffee House",
    address: "62 W Main St, Patchogue, NY",
    town: "Patchogue",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-569-4900",
    lat: 40.7654,
    lng: -72.9998,
    hours: {
      mon: "6:00 AM - 6:00 PM",
      tue: "6:00 AM - 6:00 PM",
      wed: "6:00 AM - 6:00 PM",
      thu: "6:00 AM - 8:00 PM",
      fri: "6:00 AM - 9:00 PM",
      sat: "6:00 AM - 9:00 PM",
      sun: "6:00 AM - 6:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["fresh juices", "banana chocolate chip loaf", "salted chocolate cookie"],
    vibe: ["warm", "welcoming", "laptop-friendly"],
    knownFor: "Creme brulee iced latte, cottage core chai, expanding to new locations",
    description: "Warm, welcoming, good for remote work or reading.",
    photo: null
  },
  {
    id: "southdown-patchogue",
    name: "Southdown Coffee",
    address: "16 Havens Ave, Patchogue, NY",
    town: "Patchogue",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: null,
    lat: 40.7660,
    lng: -73.0005,
    hours: {
      mon: "7:00 AM - 6:00 PM",
      tue: "7:00 AM - 6:00 PM",
      wed: "7:00 AM - 6:00 PM",
      thu: "7:00 AM - 6:00 PM",
      fri: "7:00 AM - 6:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["chickpea salad sandwich", "dark chocolate sea salt cookie (GF)"],
    vibe: ["bright", "spacious", "plant vibes"],
    knownFor: "Great drip coffee, peaceful afternoon escape",
    description: "Big windows, plants, bright/spacious. Leather sofa + plant vibes.",
    photo: null
  },
  {
    id: "toast-patchogue",
    name: "Toast Coffee + Kitchen",
    address: "46 E Main St, Patchogue, NY",
    town: "Patchogue",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-654-7091",
    lat: 40.7650,
    lng: -72.9990,
    hours: {
      mon: "8:00 AM - 3:00 PM",
      tue: "8:00 AM - 3:00 PM",
      wed: "8:00 AM - 3:00 PM",
      thu: "8:00 AM - 3:00 PM",
      fri: "8:00 AM - 3:00 PM",
      sat: "7:30 AM - 3:30 PM",
      sun: "7:30 AM - 3:30 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["Splendid Benedict", "French toast", "scrambled eggs", "full brunch"],
    vibe: ["bustling", "brunch spot"],
    knownFor: "Massive brunch menu, pink mimosas, always packed",
    description: "Popular brunch spot, bustling, counter + table seating.",
    photo: null
  },
  {
    id: "brewport-bellport",
    name: "Brewport Coffee House",
    address: "129 S Country Rd, Bellport, NY",
    town: "Bellport",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-803-0809",
    lat: 40.7568,
    lng: -72.9394,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 5:00 PM",
      sat: "7:00 AM - 5:00 PM",
      sun: "7:00 AM - 5:00 PM"
    },
    amenities: { wifi: true, bathroom: true, outlets: "plenty", seating: "indoor" },
    food: ["pastries", "seasonal baked goods"],
    vibe: ["cozy", "laptop-friendly", "quiet"],
    knownFor: "Best remote work spot in Suffolk (fast WiFi, outlets, quiet), sweater weather chai",
    description: "Cozy, great for remote work. Background music at perfect volume. Window nook + couch.",
    photo: null
  },
  {
    id: "bellport-apothecary",
    name: "Bellport Apothecary",
    address: "151 S Country Rd, Bellport, NY",
    town: "Bellport",
    region: "Suffolk",
    subregion: "Central/Eastern Suffolk",
    phone: "631-431-6825",
    lat: 40.7565,
    lng: -72.9390,
    hours: {
      mon: "8:00 AM - 5:00 PM",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["scones", "smoothies", "light bites"],
    vibe: ["boutique", "wellness", "Bellport Village charm"],
    knownFor: "Lavender lemonade tea, organic skincare products + coffee",
    description: "Coffee + boutique + wellness shop, outdoor seating, Bellport Village charm.",
    photo: null
  },

  // ============================================================
  // NORTH FORK
  // ============================================================
  {
    id: "pips-greenport",
    name: "Pip's Cafe & Provisions",
    address: "218 Main St, Greenport, NY",
    town: "Greenport",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-318-0363",
    lat: 41.1037,
    lng: -72.3598,
    hours: {
      mon: "7:30 AM - 3:00 PM",
      tue: "Closed",
      wed: "7:30 AM - 3:00 PM",
      thu: "7:30 AM - 3:00 PM",
      fri: "7:30 AM - 4:00 PM",
      sat: "7:30 AM - 4:00 PM",
      sun: "7:30 AM - 3:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["Cubano sandwich", "avo toast", "croissants", "breakfast sandwiches"],
    vibe: ["vintage records"],
    knownFor: "Counter Culture coffee, La Marzocco espresso, vintage records",
    description: "Counter Culture coffee with vintage records.",
    photo: null
  },
  {
    id: "aldos-greenport",
    name: "Aldo's Coffee Company",
    address: "103-105 Front St, Greenport, NY",
    town: "Greenport",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-213-9353",
    lat: 41.1040,
    lng: -72.3590,
    hours: {
      mon: "7:00 AM - 5:00 PM",
      tue: "7:00 AM - 5:00 PM",
      wed: "7:00 AM - 5:00 PM",
      thu: "7:00 AM - 5:00 PM",
      fri: "7:00 AM - 7:00 PM",
      sat: "7:00 AM - 6:00 PM",
      sun: "8:30 AM - 10:30 AM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["gelato", "biscotti", "chocolate croissants", "pastries"],
    vibe: ["waterfront views", "patio"],
    knownFor: "In-house roasted coffee, biscotti gifts, hot chocolate, 10+ years running",
    description: "Waterfront views, patio overlooking harbor/carousel, ice cream + coffee.",
    photo: null
  },
  {
    id: "blue-duck-greenport",
    name: "The Blue Duck Bakery Cafe",
    address: "130 Front St, Greenport, NY",
    town: "Greenport",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-333-2060",
    lat: 41.1035,
    lng: -72.3595,
    hours: {
      mon: "8:00 AM - 4:00 PM",
      tue: "8:00 AM - 4:00 PM",
      wed: "8:00 AM - 4:00 PM",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "8:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["cookies", "blueberry turnovers", "pies", "European-style pastries"],
    vibe: ["cute refurbished house", "smells like butter"],
    knownFor: "European-style baking (originally from Southampton since 1999)",
    description: "Cute refurbished house, smells like butter, tables inside + alley seating.",
    photo: null
  },
  {
    id: "north-fork-roasting-southold",
    name: "North Fork Roasting Co.",
    address: "55795 Main Rd, Southold, NY",
    town: "Southold",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-876-5450",
    lat: 41.0648,
    lng: -72.4276,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["scratch-made muffins", "breakfast sandwiches", "baked goods"],
    vibe: ["kid-friendly", "events space"],
    knownFor: "In-house roasting, strawberry matcha, best third-wave coffee on North Fork",
    description: "Upstairs rooms including kids' playroom, outdoor space for bands/events.",
    photo: null
  },
  {
    id: "panoramica-peconic",
    name: "Panoramica",
    address: "2745 Peconic Ln, Peconic, NY",
    town: "Peconic",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-765-8354",
    lat: 41.0548,
    lng: -72.4576,
    hours: {
      mon: "Closed",
      tue: "Closed",
      wed: "8:00 AM - 3:00 PM",
      thu: "8:00 AM - 3:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: "Closed"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["pastries", "light bites"],
    vibe: ["futuristic/retro", "owner-operated"],
    knownFor: "Unique design, amazing branding, creative energy",
    description: "Futuristic/retro ('The Jetsons'), fun sound effects in bathroom, owner-operated.",
    photo: null
  },
  {
    id: "love-lane-kitchen-mattituck",
    name: "Love Lane Kitchen",
    address: "240 Love Ln, Mattituck, NY",
    town: "Mattituck",
    region: "Suffolk",
    subregion: "North Fork",
    phone: "631-298-8989",
    lat: 41.0137,
    lng: -72.5342,
    hours: {
      mon: "8:00 AM - 9:00 PM",
      tue: "8:00 AM - 4:00 PM",
      wed: "8:00 AM - 4:00 PM",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 9:00 PM",
      sat: "8:00 AM - 9:00 PM",
      sun: "8:00 AM - 9:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["lobster roll", "chicken salad", "brunch", "espresso martinis"],
    vibe: ["dog-friendly patio", "farm-to-table"],
    knownFor: "Homemade chai latte, self-serve coffee refills, farm-to-table vibe",
    description: "Dog-friendly patio, self-serve coffee bar, cozy indoor/outdoor.",
    photo: null
  },

  // ============================================================
  // SOUTH FORK / HAMPTONS
  // ============================================================
  {
    id: "hampton-coffee-water-mill",
    name: "Hampton Coffee Company",
    address: "869 Montauk Hwy, Water Mill, NY",
    town: "Water Mill",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-726-2633",
    lat: 40.9192,
    lng: -72.3458,
    hours: {
      mon: "5:15 AM - 5:00 PM",
      tue: "5:15 AM - 5:00 PM",
      wed: "5:15 AM - 5:00 PM",
      thu: "5:15 AM - 5:00 PM",
      fri: "5:15 AM - 5:00 PM",
      sat: "5:15 AM - 5:00 PM",
      sun: "5:15 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["full breakfast/lunch", "Mexican items", "sandwiches", "pastries"],
    vibe: ["early bird"],
    knownFor: "Multiple Hamptons locations, opens at 5:15am, strong local loyalty",
    description: "Opens at 5:15am with full breakfast/lunch and strong local loyalty.",
    photo: null
  },
  {
    id: "hampton-coffee-southampton",
    name: "Hampton Coffee Company",
    address: "749 County Rd 39A, Southampton, NY",
    town: "Southampton",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-353-3088",
    lat: 40.8840,
    lng: -72.3897,
    hours: {
      mon: "6:00 AM - 5:00 PM",
      tue: "6:00 AM - 5:00 PM",
      wed: "6:00 AM - 5:00 PM",
      thu: "6:00 AM - 5:00 PM",
      fri: "6:00 AM - 5:00 PM",
      sat: "6:00 AM - 5:00 PM",
      sun: "6:00 AM - 5:00 PM"
    },
    amenities: { wifi: true, bathroom: null, outlets: null, seating: "indoor" },
    food: ["paninis", "muffins", "espresso drinks"],
    vibe: ["friendly"],
    knownFor: "Friendly baristas, WiFi, good grab-and-go",
    description: "Friendly baristas, WiFi, good grab-and-go.",
    photo: null
  },
  {
    id: "hampton-coffee-montauk",
    name: "Hampton Coffee Company",
    address: "732 Montauk Hwy, Montauk, NY",
    town: "Montauk",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-668-8206",
    lat: 41.0359,
    lng: -71.9546,
    hours: {
      mon: "7:00 AM - 4:00 PM",
      tue: "7:00 AM - 4:00 PM",
      wed: "7:00 AM - 4:00 PM",
      thu: "7:00 AM - 4:00 PM",
      fri: "7:00 AM - 4:00 PM",
      sat: "7:00 AM - 4:00 PM",
      sun: "7:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["bagels", "breakfast sandwiches", "baked goods"],
    vibe: ["grab-and-go"],
    knownFor: "Cinnamon roll latte",
    description: "Solid grab-and-go in Montauk.",
    photo: null
  },
  {
    id: "golden-pear-southampton",
    name: "Golden Pear Cafe",
    address: "99 Main St, Southampton, NY",
    town: "Southampton",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-283-8900",
    lat: 40.8843,
    lng: -72.3890,
    hours: {
      mon: "6:30 AM - 5:30 PM",
      tue: "6:30 AM - 5:30 PM",
      wed: "6:30 AM - 5:30 PM",
      thu: "6:30 AM - 5:30 PM",
      fri: "6:30 AM - 5:30 PM",
      sat: "6:30 AM - 5:30 PM",
      sun: "6:30 AM - 4:30 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["scones", "breakfast burritos", "salads"],
    vibe: ["neighborhood institution", "community hub"],
    knownFor: "Decades-old Hamptons staple, pricey but beloved by some",
    description: "Longtime neighborhood institution, community hub.",
    photo: null
  },
  {
    id: "tutto-caffe-east-hampton",
    name: "Tutto Caffe",
    address: "55 Main St, East Hampton, NY",
    town: "East Hampton",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-771-9030",
    lat: 40.9634,
    lng: -72.1848,
    hours: {
      mon: "8:00 AM - 5:00 PM",
      tue: "8:00 AM - 5:00 PM",
      wed: "8:00 AM - 5:00 PM",
      thu: "8:00 AM - 5:00 PM",
      fri: "8:00 AM - 5:00 PM",
      sat: "8:00 AM - 5:00 PM",
      sun: "8:00 AM - 5:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor+outdoor" },
    food: ["Roman-style pinsa pizza", "cookies", "almond flour chocolate cake"],
    vibe: ["Italian cafe", "beautiful patio", "cocktails"],
    knownFor: "Paloma cocktails, Italian pastries, great patio",
    description: "Italian cafe with beautiful patio, cocktails available.",
    photo: null
  },
  {
    id: "jacks-stir-brew-amagansett",
    name: "Jack's Stir Brew Coffee",
    address: "146 Montauk Hwy, Amagansett, NY",
    town: "Amagansett",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-267-5555",
    lat: 40.9734,
    lng: -72.1448,
    hours: {
      mon: "6:00 AM - 4:00 PM",
      tue: "6:00 AM - 4:00 PM",
      wed: "6:00 AM - 4:00 PM",
      thu: "6:00 AM - 4:00 PM",
      fri: "6:00 AM - 4:00 PM",
      sat: "6:00 AM - 4:00 PM",
      sun: "6:00 AM - 4:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "outdoor" },
    food: ["homemade biscuits", "donuts", "vegan/vegetarian options"],
    vibe: ["organic", "grab-and-go"],
    knownFor: "100% organic, triple ristretto shots only, Stella iced drink",
    description: "Grab-and-go focused, minimal seating, organic coffee, picnic tables outside.",
    photo: null
  },
  {
    id: "sett-coffee-amagansett",
    name: "Sett Coffee",
    address: "136 Main St, Amagansett, NY",
    town: "Amagansett",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-256-7831",
    lat: 40.9730,
    lng: -72.1440,
    hours: {
      mon: "Closed",
      tue: "Closed",
      wed: "7:00 AM - 1:00 PM",
      thu: "7:00 AM - 1:00 PM",
      fri: "7:00 AM - 1:00 PM",
      sat: "7:00 AM - 1:00 PM",
      sun: "7:00 AM - 1:00 PM"
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: "indoor" },
    food: ["carrot cake doughnut", "breakfast bars"],
    vibe: ["small", "neighborhood favorite"],
    knownFor: "Excellent beans, becoming a daily ritual for locals",
    description: "New, small, neighborhood favorite.",
    photo: null
  },
  {
    id: "ss-corner-shop-springs",
    name: "S&S Corner Shop",
    address: "11 Fort Pond Blvd, Springs, NY",
    town: "Springs",
    region: "Suffolk",
    subregion: "South Fork / Hamptons",
    phone: "631-268-5711",
    lat: 41.0134,
    lng: -72.1548,
    hours: {
      mon: "8:00 AM - 4:00 PM",
      tue: "Closed",
      wed: "8:00 AM - 4:00 PM",
      thu: "8:00 AM - 4:00 PM",
      fri: "8:00 AM - 4:00 PM",
      sat: "8:00 AM - 4:00 PM",
      sun: null
    },
    amenities: { wifi: null, bathroom: null, outlets: null, seating: null },
    food: ["pastries from Pain d'Avignon"],
    vibe: ["Brooklyn transplant feel", "general store"],
    knownFor: "Variety coffee, art books, local jewelry, no real seating (bench only)",
    description: "Brooklyn transplant feel (Fort Greene vibes), coffee + general store + vinyl/art books.",
    photo: null
  }
];

export default coffeeShops;
